export const guards = [
    {
        id: 1,
        name: "John Smith",
        _id: "#GRD-0007",
        idNumber: "15511021",
        type: "Corporate",
        cardNumber: "15511021",
        phoneNumber: "+12635825",
        driverLicenseNumber: "123 568 223",
        issuingState: "California",
        city: "Los Angeles",
        checkInTime: "09:40 PM",
        status: "On Duty",
        locationRating: "4.8",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 2,
        name: "Maria Garcia",
        _id: "#GRD-0008",
        idNumber: "15511022",
        type: "Unarmed",
        cardNumber: "15511022",
        phoneNumber: "+12635826",
        driverLicenseNumber: "123 568 224",
        issuingState: "Texas",
        city: "Houston",
        checkInTime: "10:00 PM",
        status: "Day off",
        locationRating: "4.7",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 3,
        name: "Robert Johnson",
        _id: "#GRD-0009",
        idNumber: "15511023",
        type: "Armed",
        cardNumber: "15511023",
        phoneNumber: "+12635827",
        driverLicenseNumber: "123 568 225",
        issuingState: "Florida",
        city: "Miami",
        checkInTime: "10:00 PM",
        status: "In Progress (PhotoPending)",
        locationRating: "4.9",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 4,
        name: "Sarah Williams",
        _id: "#GRD-0010",
        idNumber: "15511024",
        type: "Corporate",
        cardNumber: "15511024",
        phoneNumber: "+12635828",
        driverLicenseNumber: "123 568 226",
        issuingState: "New York",
        city: "Brooklyn",
        checkInTime: "10:00 PM",
        status: "Late (Arrived 12:11 AM)",
        locationRating: "4.6",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 5,
        name: "Michael Brown",
        _id: "#GRD-0011",
        idNumber: "15511025",
        type: "Armed",
        cardNumber: "15511025",
        phoneNumber: "+12635829",
        driverLicenseNumber: "123 568 227",
        issuingState: "Illinois",
        city: "Chicago",
        checkInTime: "Missed Check-In",
        status: "Missed Check-In",
        locationRating: "4.5",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 6,
        name: "Jennifer Davis",
        _id: "#GRD-0012",
        idNumber: "15511026",
        type: "Armed",
        cardNumber: "15511026",
        phoneNumber: "+12635830",
        driverLicenseNumber: "123 568 228",
        issuingState: "Arizona",
        city: "Phoenix",
        checkInTime: "11:00 PM",
        status: "Off Duty",
        locationRating: "4.8",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 7,
        name: "David Miller",
        _id: "#GRD-0013",
        idNumber: "15511027",
        type: "Corporate",
        cardNumber: "15511027",
        phoneNumber: "+12635831",
        driverLicenseNumber: "123 568 229",
        issuingState: "Nevada",
        city: "Las Vegas",
        checkInTime: "08:30 PM",
        status: "On Duty",
        locationRating: "4.9",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 8,
        name: "Lisa Wilson",
        _id: "#GRD-0014",
        idNumber: "15511028",
        type: "Unarmed",
        cardNumber: "15511028",
        phoneNumber: "+12635832",
        driverLicenseNumber: "123 568 230",
        issuingState: "Washington",
        city: "Seattle",
        checkInTime: "09:15 PM",
        status: "On Duty",
        locationRating: "4.7",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 9,
        name: "James Taylor",
        _id: "#GRD-0015",
        idNumber: "15511029",
        type: "Armed",
        cardNumber: "15511029",
        phoneNumber: "+12635833",
        driverLicenseNumber: "123 568 231",
        issuingState: "Colorado",
        city: "Denver",
        checkInTime: "10:45 PM",
        status: "In Progress (PhotoPending)",
        locationRating: "4.6",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    },
    {
        id: 10,
        name: "Emily Anderson",
        _id: "#GRD-0016",
        idNumber: "15511030",
        type: "Corporate",
        cardNumber: "15511030",
        phoneNumber: "+12635834",
        driverLicenseNumber: "123 568 232",
        issuingState: "Georgia",
        city: "Atlanta",
        checkInTime: "09:00 PM",
        status: "On Duty",
        locationRating: "4.8",
        locationIcon: "🚠️",
        avatar: "/images/avatar.png"
    }
];
