import { Duty } from "@/app/types/duty";

export const duties: Duty[] = [
  {
    row: 1,
    title: "Split Shift",
    date: "11/14/2025",
    site: "Site Name",
    guard_name: "Guard Name",
    mandatory_check_in: 8,
    required_hours: 8,
    check_in: "12:32",
    check_out: "20:32",
    total_working_hours: 8,
    status: "Shift completed",
  },
  {
    row: 2,
    title: "Weekend Shift",
    date: "11/14/2025",
    site: "Site Name",
    guard_name: "Guard Name",
    mandatory_check_in: 8,
    required_hours: 8,
    check_in: "12:32",
    check_out: null,
    total_working_hours: null,
    status: "On Duty",
  },
  {
    row: 3,
    title: "Swing Shift",
    date: "11/14/2025",
    site: "Site Name",
    guard_name: "Guard Name",
    mandatory_check_in: 8,
    required_hours: 8,
    check_in: "12:32",
    check_out: null,
    total_working_hours: null,
    status: "In Progress",
  },
  {
    row: 4,
    title: "Night Shift",
    date: "11/14/2025",
    site: "Site Name",
    guard_name: "Guard Name",
    mandatory_check_in: 8,
    required_hours: 8,
    check_in: "12:11",
    check_out: null,
    total_working_hours: null,
    status: "Late",
  },
  {
    row: 5,
    title: "Morning Shift",
    date: "11/14/2025",
    site: "Site Name",
    guard_name: "Guard Name",
    mandatory_check_in: 8,
    required_hours: 8,
    check_in: null,
    check_out: null,
    total_working_hours: null,
    status: "Missed Check-in",
  },
  {
    row: 6,
    title: "Morning Shift",
    date: "11/14/2025",
    site: "Site Name",
    guard_name: "Guard Name",
    mandatory_check_in: 8,
    required_hours: 8,
    check_in: "12:32",
    check_out: "12:32",
    total_working_hours: 0,
    status: "On Duty",
  },
];