'use client'
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { ReactNode, useState, useEffect, useRef } from 'react'
import Image from "next/image"
import { FloatingLabelInput } from "../ui/floating-input"
import { FloatingLabelSelect } from "../ui/floating-select"
import { FloatingLabelTextarea } from "../ui/floating-textarea"
import {
    Plus,
    UploadCloud,
    X,
    Building,
    Contact,
    FileText,
    Copy,
    Globe,
    MapPin,
    Calendar,
    Link,
    User,
    Phone,
    Briefcase,
    Award
} from "lucide-react"
import { useForm, Controller, useFieldArray } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { useAppDispatch } from "@/hooks/useAppDispatch"
import { createClient, fetchClients } from "@/store/slices/clientSlice"
import SweetAlertService from "@/lib/sweetAlert"
import {
    clientBasicSchema,
    ClientFormData,
    SiteFormData,
    ContactFormData
} from "@/lib/validation/client.schema"
import {
    COUNTRIES,
    BUSINESS_TYPES,
    INDUSTRIES,
    CLIENT_DOCUMENT_TYPES,
    SITE_DOCUMENT_TYPES
} from "@/lib/validation/client.types"
import { Textarea } from "../ui/textarea"
import { DialogTitle } from "@radix-ui/react-dialog"

interface ClientCreateFormProps {
    trigger: ReactNode
    isOpen?: boolean
    onOpenChange?: (open: boolean) => void
    onSuccess?: () => void
    lastClientCode?: string // Optional: last client code from API
}

export function ClientCreateForm({
    trigger,
    isOpen,
    onOpenChange,
    onSuccess,
    lastClientCode
}: ClientCreateFormProps) {
    const dispatch = useAppDispatch()
    const [isSubmitting, setIsSubmitting] = useState(false)
    const [profileImage, setProfileImage] = useState<File | null>(null)
    const [documents, setDocuments] = useState<File[]>([])
    const [selectedDocumentTypes, setSelectedDocumentTypes] = useState<string[]>([])
    const [step, setStep] = useState(1)
    const [autoGeneratedCode, setAutoGeneratedCode] = useState<string>("")
    const [isGeneratingCode, setIsGeneratingCode] = useState(false)
    const clientCodeRef = useRef<HTMLInputElement>(null)

    const {
        control,
        register,
        handleSubmit,
        formState: { errors },
        reset,
        watch,
        setValue,
        trigger: triggerValidation,
        clearErrors,
    } = useForm<ClientFormData>({
        resolver: zodResolver(clientBasicSchema),
        defaultValues: {
            is_active: true,
            full_name: "",
            email: "",
            phone: "",
            password: "",
            client_code: "",
            company_name: "",
            tax_id: "",
            country: "",
            city: "",
            address: "",
            zip_code: "",
            currency_id: undefined,
            registration_date: "",
            business_type: "",
            industry: "",
            website: "",
            contact_person: "",
            contact_person_phone: "",
            license_number: "",
            notes: "",
            contacts: [],
            sites: [],
            client_document_types: [],
            site_document_types: [],
            media_categories: []
        },
        mode: "onChange",
    })

    // UseFieldArray for contacts and sites
    const {
        fields: contactFields,
        append: appendContact,
        remove: removeContact
    } = useFieldArray({
        control,
        name: "contacts"
    })

    const {
        fields: siteFields,
        append: appendSite,
        remove: removeSite
    } = useFieldArray({
        control,
        name: "sites"
    })

    // Function to generate client code in format: CL-YYYY-XXX
    const generateClientCode = async (): Promise<string> => {
        try {
            setIsGeneratingCode(true)

            // Get current year
            const currentYear = new Date().getFullYear()

            // If we have lastClientCode from props, use it to generate next number
            let nextNumber = 1

            if (lastClientCode) {
                // Parse last code format: CL-YYYY-XXX
                const match = lastClientCode.match(/CL-(\d{4})-(\d+)/)
                if (match && match[2]) {
                    nextNumber = parseInt(match[2]) + 1
                }
            } else {
                // Try to fetch clients to get the last code
                try {
                    const result = await dispatch(fetchClients({ page: 1, per_page: 1 }))
                    if (fetchClients.fulfilled.match(result)) {
                        const clients = result.payload.items
                        if (clients.length > 0) {
                            // Sort clients by ID to get the last one
                            const sortedClients = [...clients].sort((a, b) => b.id - a.id)
                            const lastClient = sortedClients[0]

                            if (lastClient.client_code) {
                                const match = lastClient.client_code.match(/CL-(\d{4})-(\d+)/)
                                if (match && match[2]) {
                                    nextNumber = parseInt(match[2]) + 1
                                }
                            }
                        }
                    }
                } catch (error) {
                    console.warn("Could not fetch clients for code generation:", error)
                }
            }

            // Format number with leading zeros (001, 002, etc.)
            const formattedNumber = nextNumber.toString().padStart(3, '0')

            // Return formatted code
            return `CL-${currentYear}-${formattedNumber}`
        } catch (error) {
            console.error("Error generating client code:", error)
            // Fallback: generate a random code
            const currentYear = new Date().getFullYear()
            const randomNum = Math.floor(Math.random() * 900) + 100 // 100-999
            return `CL-${currentYear}-${randomNum}`
        } finally {
            setIsGeneratingCode(false)
        }
    }

    // Initialize form with generated client code when dialog opens
    useEffect(() => {
        const initializeForm = async () => {
            if (isOpen) {
                const generatedCode = await generateClientCode()
                setAutoGeneratedCode(generatedCode)
                setValue("client_code", generatedCode)

                // Add initial contact
                if (contactFields.length === 0) {
                    appendContact({
                        name: "",
                        phone: "",
                        email: "",
                        position: "",
                        department: "",
                        is_primary: true,
                        notes: ""
                    })
                }
            }
        }

        initializeForm()
    }, [isOpen, setValue, lastClientCode])

    // Copy client code to clipboard
    const copyClientCode = () => {
        if (clientCodeRef.current) {
            clientCodeRef.current.select()
            navigator.clipboard.writeText(autoGeneratedCode)
            SweetAlertService.success(
                "Copied!",
                "Client code copied to clipboard.",
                {
                    timer: 1500,
                    showConfirmButton: false,
                }
            )
        }
    }

    // Regenerate client code
    const regenerateClientCode = async () => {
        const newCode = await generateClientCode()
        setAutoGeneratedCode(newCode)
        setValue("client_code", newCode)

        SweetAlertService.info(
            "Code Regenerated",
            "New client code has been generated.",
            {
                timer: 1500,
                showConfirmButton: false,
            }
        )
    }

    const handleProfileImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            if (!file.type.startsWith('image/')) {
                SweetAlertService.error("Invalid file type", "Please upload an image file")
                return
            }
            if (file.size > 5 * 1024 * 1024) {
                SweetAlertService.error("File too large", "Please upload an image smaller than 5MB")
                return
            }
            setProfileImage(file)
        }
    }

    const handleDocumentUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const files = Array.from(e.target.files || [])
        const validFiles = files.filter(file => {
            const validTypes = [
                'application/pdf',
                'image/jpeg',
                'image/png',
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            ]
            return validTypes.includes(file.type) && file.size <= 10 * 1024 * 1024
        })

        if (validFiles.length !== files.length) {
            SweetAlertService.warning("Some files were skipped", "Only PDF, JPG, PNG, and DOC files up to 10MB are allowed")
        }

        setDocuments(prev => [...prev, ...validFiles])
    }

    const removeDocument = (index: number) => {
        setDocuments(prev => prev.filter((_, i) => i !== index))
    }

    const handleDocumentTypeChange = (docType: string) => {
        const newSelectedTypes = selectedDocumentTypes.includes(docType)
            ? selectedDocumentTypes.filter(type => type !== docType)
            : [...selectedDocumentTypes, docType]

        setSelectedDocumentTypes(newSelectedTypes)
        setValue("client_document_types", newSelectedTypes, { shouldValidate: true })
    }

    const handleSiteDocumentTypeChange = (docType: string, siteIndex: number) => {
        const currentSite = siteFields[siteIndex]
        if (!currentSite) return

        const currentTypes = currentSite.site_document_types || []
        const newTypes = currentTypes.includes(docType)
            ? currentTypes.filter(type => type !== docType)
            : [...currentTypes, docType]

        // Update the specific site's document types
        setValue(`sites.${siteIndex}.site_document_types`, newTypes)
    }

    const addContact = () => {
        appendContact({
            name: "",
            phone: "",
            email: "",
            position: "",
            department: "",
            is_primary: contactFields.length === 0, // First contact is primary
            notes: ""
        })
    }

    const addSite = () => {
        appendSite({
            site_name: "",
            site_instruction: "",
            address: "",
            guards_required: 1,
            latitude: 0,
            longitude: 0,
            status: "planned",
            locations: [],
            site_document_types: []
        })
    }

    const addLocationToSite = (siteIndex: number) => {
        const currentSite = siteFields[siteIndex]
        if (!currentSite) return

        const currentLocations = currentSite.locations || []
        const newLocations = [
            ...currentLocations,
            {
                title: "",
                description: "",
                latitude: 0,
                longitude: 0,
                is_active: true
            }
        ]

        setValue(`sites.${siteIndex}.locations`, newLocations)
    }

    const removeLocationFromSite = (siteIndex: number, locationIndex: number) => {
        const currentSite = siteFields[siteIndex]
        if (!currentSite || !currentSite.locations) return

        const newLocations = [...currentSite.locations]
        newLocations.splice(locationIndex, 1)
        setValue(`sites.${siteIndex}.locations`, newLocations)
    }

    const setPrimaryContact = (index: number) => {
        // Set all contacts to non-primary first
        contactFields.forEach((_, i) => {
            setValue(`contacts.${i}.is_primary`, i === index)
        })
    }

    const onSubmit = async (data: ClientFormData) => {
        setIsSubmitting(true)

        try {
            // Create FormData
            const formData = new FormData()

            // Use the auto-generated code if client_code is empty
            const finalClientCode = data.client_code || autoGeneratedCode

            // Append all form fields
            Object.entries(data).forEach(([key, value]) => {
                if (value !== undefined && value !== null) {
                    if (key === 'contacts' || key === 'sites') {
                        // Stringify arrays
                        formData.append(key, JSON.stringify(value || []))
                    } else if (key === 'client_document_types' || key === 'media_categories') {
                        // Stringify arrays
                        formData.append(key, JSON.stringify(value || []))
                    } else if (typeof value === 'boolean') {
                        formData.append(key, value ? '1' : '0')
                    } else if (typeof value === 'number') {
                        formData.append(key, value.toString())
                    } else {
                        formData.append(key, value.toString())
                    }
                }
            })

            // Ensure client code is included
            formData.append('client_code', finalClientCode)

            // Append files
            if (profileImage) {
                formData.append('profile_image', profileImage)
            }

            documents.forEach((doc, index) => {
                formData.append(`documents[${index}]`, doc)
            })

            // Dispatch create client action
            const result = await dispatch(createClient(formData))

            if (createClient.fulfilled.match(result)) {
                SweetAlertService.success(
                    'Client Created Successfully',
                    `${data.company_name || data.full_name} has been created with code: ${finalClientCode}`,
                    {
                        timer: 2000,
                        showConfirmButton: false,
                    }
                )

                // Reset form
                reset({
                    is_active: true,
                    full_name: "",
                    email: "",
                    phone: "",
                    password: "",
                    client_code: "",
                    company_name: "",
                    tax_id: "",
                    country: "",
                    city: "",
                    address: "",
                    zip_code: "",
                    currency_id: undefined,
                    registration_date: "",
                    business_type: "",
                    industry: "",
                    website: "",
                    contact_person: "",
                    contact_person_phone: "",
                    license_number: "",
                    notes: "",
                    contacts: [{
                        name: "",
                        phone: "",
                        email: "",
                        position: "",
                        department: "",
                        is_primary: true,
                        notes: ""
                    }],
                    sites: [],
                    client_document_types: [],
                    site_document_types: [],
                    media_categories: []
                })

                // Clear UI state
                setProfileImage(null)
                setDocuments([])
                setSelectedDocumentTypes([])
                setStep(1)

                // Clear errors
                clearErrors()

                // Generate new code for next client
                const newCode = await generateClientCode()
                setAutoGeneratedCode(newCode)
                setValue("client_code", newCode)

                // Call success callback
                if (onSuccess) onSuccess()
                if (onOpenChange) onOpenChange(false)
            } else {
                throw new Error(result.payload as string || 'Failed to create client')
            }
        } catch (error) {
            SweetAlertService.error(
                'Creation Failed',
                error instanceof Error ? error.message : 'There was an error creating the client. Please try again.'
            )
            console.error('Error creating client:', error)
        } finally {
            setIsSubmitting(false)
        }
    }

    const validateStep = async (currentStep: number): Promise<boolean> => {
        let fieldsToValidate: string[] = []

        if (currentStep === 1) {
            fieldsToValidate = [
                'full_name', 'email', 'phone', 'password',
                'company_name', 'country', 'city', 'address'
            ]
        } else if (currentStep === 2) {
            // Validate at least one contact
            if (contactFields.length === 0) {
                SweetAlertService.warning(
                    'Contacts Required',
                    'Please add at least one contact person.',
                    {
                        timer: 3000,
                        showConfirmButton: true,

                    }
                )
                return false
            }

            // Validate primary contact has required fields
            const primaryContactIndex = contactFields.findIndex((_, i) => watch(`contacts.${i}.is_primary`))
            if (primaryContactIndex !== -1) {
                fieldsToValidate = [
                    `contacts.${primaryContactIndex}.name`,
                    `contacts.${primaryContactIndex}.phone`
                ]
            }
        }

        if (fieldsToValidate.length > 0) {
            const result = await triggerValidation(fieldsToValidate as any, { shouldFocus: true })
            return result
        }

        return true
    }

    const nextStep = async () => {
        const isValid = await validateStep(step)
        if (isValid) {
            setStep(step + 1)
        } else {
            SweetAlertService.warning(
                'Incomplete Information',
                'Please fill in all required fields correctly before proceeding.',
                {
                    timer: 3000,
                    showConfirmButton: true,
                    confirmButtonText: 'OK',
                    didClose: () => {
                        const firstErrorKey = Object.keys(errors)[0]
                        if (firstErrorKey) {
                            const element = document.querySelector(`[name="${firstErrorKey}"]`)
                            if (element) {
                                (element as HTMLElement).focus()
                            }
                        }
                    }
                }
            )
        }
    }

    const prevStep = () => {
        setStep(step - 1)
    }

    const getCurrentDate = () => {
        const today = new Date()
        return today.toISOString().split('T')[0]
    }

    const getMaxDate = () => {
        const maxDate = new Date()
        maxDate.setFullYear(maxDate.getFullYear() + 10)
        return maxDate.toISOString().split('T')[0]
    }

    // Add a function to handle dialog close
    const handleDialogClose = () => {
        if (onOpenChange) {
            onOpenChange(false);
        }
    };

    // Add a function to handle form reset on close
    const handleCancel = () => {
        // Reset form
        reset({
            is_active: true,
            full_name: "",
            email: "",
            phone: "",
            password: "",
            client_code: "",
            company_name: "",
            tax_id: "",
            country: "",
            city: "",
            address: "",
            zip_code: "",
            currency_id: undefined,
            registration_date: "",
            business_type: "",
            industry: "",
            website: "",
            contact_person: "",
            contact_person_phone: "",
            license_number: "",
            notes: "",
            contacts: [{
                name: "",
                phone: "",
                email: "",
                position: "",
                department: "",
                is_primary: true,
                notes: ""
            }],
            sites: [],
            client_document_types: [],
            site_document_types: [],
            media_categories: []
        });

        // Clear UI state
        setProfileImage(null);
        setDocuments([]);
        setSelectedDocumentTypes([]);
        setStep(1);

        // Clear errors
        clearErrors();

        // Close dialog
        handleDialogClose();
    };

    return (
        <Dialog open={isOpen} onOpenChange={onOpenChange}>
            <DialogTrigger asChild>
                {trigger}
            </DialogTrigger>

            <DialogContent className="sm:max-w-[1200px] w-[95vw] max-w-[95vw] mx-auto max-h-[90vh] overflow-y-auto dark:bg-gray-900 p-4 sm:p-6">
                <DialogTitle></DialogTitle>

                {/* Header */}
                <div className="flex items-center gap-2 text-lg font-semibold mb-6">
                    <Image src="/images/logo.png" alt="Logo" width={24} height={24} />
                    <span className="whitespace-nowrap">Add New Client</span>
                </div>

                {/* Validation Errors Debug */}
                {/* {Object.keys(errors).length > 0 && (
                    <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-md">
                        <p className="text-sm font-medium text-red-800">Validation Errors:</p>
                        <ul className="mt-1 text-sm text-red-600">
                            {Object.entries(errors).map(([key, error]) => (
                                <li key={key}>
                                    {key}: {error?.message || 'Invalid'}
                                </li>
                            ))}
                        </ul>
                    </div>
                )} */}

                {/* Progress Steps */}
                <div className="flex items-center justify-center mb-6">
                    <div className="flex items-center space-x-2">
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 1 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                            <Building size={20} />
                        </div>
                        <div className={`w-16 h-1 ${step >= 2 ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 2 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                            <Contact size={20} />
                        </div>
                        <div className={`w-16 h-1 ${step >= 3 ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 3 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                            <MapPin size={20} />
                        </div>
                        <div className={`w-16 h-1 ${step >= 4 ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 4 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                            <FileText size={20} />
                        </div>
                    </div>
                </div>

                <form onSubmit={handleSubmit(onSubmit)}>
                    {step === 1 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <Building size={20} />
                                Company Information
                            </h3>

                            {/* Client Code Section */}
                            <div className="mb-6 bg-blue-50 dark:bg-gray-800 rounded-lg p-4">
                                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                                    <div>
                                        <h4 className="font-semibold text-gray-700 dark:text-gray-300">
                                            Client Code
                                        </h4>
                                        <p className="text-sm text-gray-600 dark:text-gray-400">
                                            Automatically generated unique identifier
                                        </p>
                                    </div>

                                    <div className="flex items-center gap-2">
                                        <div className="relative">
                                            <input
                                                ref={clientCodeRef}
                                                type="text"
                                                value={autoGeneratedCode}
                                                readOnly
                                                className="w-full px-4 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg font-mono text-lg font-bold text-center"
                                            />
                                            {isGeneratingCode && (
                                                <div className="absolute inset-0 flex items-center justify-center bg-white bg-opacity-80 dark:bg-gray-700">
                                                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600"></div>
                                                </div>
                                            )}
                                        </div>

                                        <div className="flex gap-1">
                                            <Button
                                                type="button"
                                                size="sm"
                                                variant="outline"
                                                onClick={copyClientCode}
                                                className="h-9"
                                            >
                                                <Copy size={16} />
                                            </Button>
                                            <Button
                                                type="button"
                                                size="sm"
                                                variant="outline"
                                                onClick={regenerateClientCode}
                                                disabled={isGeneratingCode}
                                                className="h-9"
                                            >
                                                Regenerate
                                            </Button>
                                        </div>
                                    </div>
                                </div>

                                {/* Hidden input for form submission */}
                                <input
                                    type="hidden"
                                    {...register("client_code")}
                                    value={autoGeneratedCode}
                                    onChange={() => { }}
                                />
                            </div>

                            {/* First Row - Personal/Company Info */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
                                {/* Full Name */}
                                <div>
                                    <Controller
                                        name="full_name"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Contact Person Name *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.full_name?.message}
                                                icon={<User size={16} />}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Company Name */}
                                <div>
                                    <Controller
                                        name="company_name"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Company Name *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.company_name?.message}
                                                icon={<Building size={16} />}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Email */}
                                <div>
                                    <Controller
                                        name="email"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Email *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                type="email"
                                                error={errors.email?.message}
                                                placeholder="company@example.com"
                                            />
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Second Row - Contact & Tax */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
                                {/* Phone */}
                                <div>
                                    <Controller
                                        name="phone"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Phone Number *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                type="tel"
                                                error={errors.phone?.message}
                                                icon={<Phone size={16} />}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Tax ID */}
                                <div>
                                    <Controller
                                        name="tax_id"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Tax ID / TRN"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                placeholder="e.g., TRN-123456789"
                                            />
                                        )}
                                    />
                                </div>

                                {/* License Number */}
                                <div>
                                    <Controller
                                        name="license_number"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="License Number"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                placeholder="e.g., TRN-789012345"
                                                icon={<Award size={16} />}
                                            />
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Third Row - Location */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                {/* Country */}
                                <div>
                                    <Controller
                                        name="country"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Country *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.country?.message}
                                                icon={<Globe size={16} />}
                                            >
                                                <option value="">Select Country...</option>
                                                {COUNTRIES.map(country => (
                                                    <option key={country.code} value={country.name}>
                                                        {country.name}
                                                    </option>
                                                ))}
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>

                                {/* City */}
                                <div>
                                    <Controller
                                        name="city"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="City *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.city?.message}
                                                icon={<MapPin size={16} />}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Address */}
                                <div className="md:col-span-2">
                                    <Controller
                                        name="address"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Address *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.address?.message}
                                            />
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Fourth Row - Additional Info */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                {/* Zip Code */}
                                <div>
                                    <Controller
                                        name="zip_code"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Zip/Postal Code"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Business Type */}
                                <div>
                                    <Controller
                                        name="business_type"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Business Type"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            >
                                                <option value="">Select Type...</option>
                                                {BUSINESS_TYPES.map(type => (
                                                    <option key={type} value={type}>{type}</option>
                                                ))}
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>

                                {/* Industry */}
                                <div>
                                    <Controller
                                        name="industry"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Industry"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            >
                                                <option value="">Select Industry...</option>
                                                {INDUSTRIES.map(industry => (
                                                    <option key={industry} value={industry}>{industry}</option>
                                                ))}
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>

                                {/* Registration Date */}
                                <div>
                                    <Controller
                                        name="registration_date"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Registration Date"
                                                type="date"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                max={getCurrentDate()}
                                                icon={<Calendar size={16} />}
                                            />
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Fifth Row - Website & Contact */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                {/* Website */}
                                <div className="md:col-span-2">
                                    <Controller
                                        name="website"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Website"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                type="url"
                                                placeholder="https://example.com"
                                                icon={<Link size={16} />}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Contact Person */}
                                <div>
                                    <Controller
                                        name="contact_person"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Contact Person"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                placeholder="Main contact name"
                                            />
                                        )}
                                    />
                                </div>

                                {/* Contact Person Phone */}
                                <div>
                                    <Controller
                                        name="contact_person_phone"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Contact Phone"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                type="tel"
                                                placeholder="+971501234568"
                                            />
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Password & Notes Row */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                                {/* Password */}
                                <div>
                                    <Controller
                                        name="password"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Password *"
                                                type="password"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.password?.message}
                                                placeholder="Min. 6 characters"
                                            />
                                        )}
                                    />
                                </div>

                                {/* Notes */}
                                <div>
                                    <Controller
                                        name="notes"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelTextarea
                                                label="Notes"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                placeholder="Any additional information about the client..."
                                                className="h-32 resize-none"
                                            />
                                        )}
                                    />
                                </div>
                            </div>
                        </div>
                    )}

                    {step === 2 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <Contact size={20} />
                                Contact Persons
                            </h3>

                            <div className="mb-6">
                                <div className="flex justify-between items-center mb-4">
                                    <p className="text-gray-600 dark:text-gray-400">
                                        Add contact persons for this client. At least one primary contact is required.
                                    </p>
                                    <Button
                                        type="button"
                                        onClick={addContact}
                                        variant="outline"
                                        size="sm"
                                    >
                                        <Plus size={16} className="mr-1" />
                                        Add Contact
                                    </Button>
                                </div>

                                {/* Contacts List */}
                                {contactFields.map((contact, index) => (
                                    <div key={contact.id} className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4 mb-4">
                                        <div className="flex justify-between items-center mb-3">
                                            <div className="flex items-center gap-2">
                                                <Contact size={18} />
                                                <h4 className="font-semibold">
                                                    Contact {index + 1}
                                                </h4>
                                                {watch(`contacts.${index}.is_primary`) && (
                                                    <span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded-full">
                                                        Primary
                                                    </span>
                                                )}
                                            </div>
                                            <div className="flex gap-2">
                                                {!watch(`contacts.${index}.is_primary`) && (
                                                    <Button
                                                        type="button"
                                                        onClick={() => setPrimaryContact(index)}
                                                        variant="outline"
                                                        size="sm"
                                                    >
                                                        Set as Primary
                                                    </Button>
                                                )}
                                                {contactFields.length > 1 && (
                                                    <Button
                                                        type="button"
                                                        onClick={() => removeContact(index)}
                                                        variant="ghost"
                                                        size="sm"
                                                        className="text-red-500 hover:text-red-700"
                                                    >
                                                        <X size={16} />
                                                    </Button>
                                                )}
                                            </div>
                                        </div>

                                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                                            {/* Name */}
                                            <div>
                                                <Controller
                                                    name={`contacts.${index}.name`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Name *"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            error={errors.contacts?.[index]?.name?.message}
                                                            disabled={watch(`contacts.${index}.is_primary`)}
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Phone */}
                                            <div>
                                                <Controller
                                                    name={`contacts.${index}.phone`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Phone *"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            type="tel"
                                                            error={errors.contacts?.[index]?.phone?.message}
                                                            disabled={watch(`contacts.${index}.is_primary`)}
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Email */}
                                            <div>
                                                <Controller
                                                    name={`contacts.${index}.email`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Email"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            type="email"
                                                            disabled={watch(`contacts.${index}.is_primary`)}
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Position */}
                                            <div>
                                                <Controller
                                                    name={`contacts.${index}.position`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Position"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            disabled={watch(`contacts.${index}.is_primary`)}
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Department */}
                                            <div>
                                                <Controller
                                                    name={`contacts.${index}.department`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Department"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            disabled={watch(`contacts.${index}.is_primary`)}
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Notes */}
                                            <div className="md:col-span-3">
                                                <Controller
                                                    name={`contacts.${index}.notes`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelTextarea
                                                            label="Notes"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            placeholder="Additional information about this contact..."
                                                            className="h-20 resize-none"
                                                            disabled={watch(`contacts.${index}.is_primary`)}
                                                        />
                                                    )}
                                                />
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {step === 3 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <MapPin size={20} />
                                Sites & Locations
                            </h3>

                            <div className="mb-6">
                                <div className="flex justify-between items-center mb-4">
                                    <p className="text-gray-600 dark:text-gray-400">
                                        Add sites that require security services. You can add multiple locations for each site.
                                    </p>
                                    <Button
                                        type="button"
                                        onClick={addSite}
                                        variant="outline"
                                        size="sm"
                                    >
                                        <Plus size={16} className="mr-1" />
                                        Add Site
                                    </Button>
                                </div>

                                {/* Sites List */}
                                {siteFields.map((site, siteIndex) => (
                                    <div key={site.id} className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4 mb-6">
                                        <div className="flex justify-between items-center mb-4">
                                            <div className="flex items-center gap-2">
                                                <MapPin size={18} />
                                                <h4 className="font-semibold">
                                                    Site {siteIndex + 1}: {watch(`sites.${siteIndex}.site_name`) || 'Unnamed Site'}
                                                </h4>
                                            </div>
                                            <Button
                                                type="button"
                                                onClick={() => removeSite(siteIndex)}
                                                variant="ghost"
                                                size="sm"
                                                className="text-red-500 hover:text-red-700"
                                            >
                                                <X size={16} />
                                            </Button>
                                        </div>

                                        {/* Site Details */}
                                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
                                            {/* Site Name */}
                                            <div>
                                                <Controller
                                                    name={`sites.${siteIndex}.site_name`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Site Name *"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            error={errors.sites?.[siteIndex]?.site_name?.message}
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Guards Required */}
                                            <div>
                                                <Controller
                                                    name={`sites.${siteIndex}.guards_required`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Guards Required *"
                                                            type="number"
                                                            min="1"
                                                            value={field.value?.toString() || '1'}
                                                            onChange={(e) => field.onChange(parseInt(e.target.value) || 1)}
                                                            error={errors.sites?.[siteIndex]?.guards_required?.message}
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Status */}
                                            <div>
                                                <Controller
                                                    name={`sites.${siteIndex}.status`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelSelect
                                                            label="Status *"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            error={errors.sites?.[siteIndex]?.status?.message}
                                                        >
                                                            <option value="">Select Status...</option>
                                                            <option value="planned">Planned</option>
                                                            <option value="running">Running</option>
                                                            <option value="paused">Paused</option>
                                                            <option value="completed">Completed</option>
                                                        </FloatingLabelSelect>
                                                    )}
                                                />
                                            </div>

                                            {/* Address */}
                                            <div className="md:col-span-2">
                                                <Controller
                                                    name={`sites.${siteIndex}.address`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Address *"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            error={errors.sites?.[siteIndex]?.address?.message}
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Site Instructions */}
                                            <div className="md:col-span-3">
                                                <Controller
                                                    name={`sites.${siteIndex}.site_instruction`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelTextarea
                                                            label="Site Instructions"
                                                            value={field.value || ''}
                                                            onChange={field.onChange}
                                                            placeholder="Special instructions for this site..."
                                                            className="h-24 resize-none"
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Coordinates */}
                                            <div>
                                                <Controller
                                                    name={`sites.${siteIndex}.latitude`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Latitude"
                                                            type="number"
                                                            step="any"
                                                            value={field.value?.toString() || ''}
                                                            onChange={(e) => field.onChange(parseFloat(e.target.value) || 0)}
                                                            placeholder="25.197197"
                                                        />
                                                    )}
                                                />
                                            </div>

                                            <div>
                                                <Controller
                                                    name={`sites.${siteIndex}.longitude`}
                                                    control={control}
                                                    render={({ field }) => (
                                                        <FloatingLabelInput
                                                            label="Longitude"
                                                            type="number"
                                                            step="any"
                                                            value={field.value?.toString() || ''}
                                                            onChange={(e) => field.onChange(parseFloat(e.target.value) || 0)}
                                                            placeholder="55.274372"
                                                        />
                                                    )}
                                                />
                                            </div>

                                            {/* Site Document Types */}
                                            <div>
                                                <label className="block text-sm font-medium mb-2">
                                                    Site Documents
                                                </label>
                                                <div className="flex flex-wrap gap-2">
                                                    {SITE_DOCUMENT_TYPES.map((docType) => (
                                                        <label key={docType.id} className="flex items-center gap-1">
                                                            <input
                                                                type="checkbox"
                                                                checked={watch(`sites.${siteIndex}.site_document_types`)?.includes(docType.id) || false}
                                                                onChange={() => handleSiteDocumentTypeChange(docType.id, siteIndex)}
                                                                className="rounded"
                                                            />
                                                            <span className="text-xs">{docType.name}</span>
                                                        </label>
                                                    ))}
                                                </div>
                                            </div>
                                        </div>

                                        {/* Locations for this site */}
                                        <div className="mb-4">
                                            <div className="flex justify-between items-center mb-3">
                                                <h5 className="font-medium">Locations within Site</h5>
                                                <Button
                                                    type="button"
                                                    onClick={() => addLocationToSite(siteIndex)}
                                                    variant="outline"
                                                    size="sm"
                                                >
                                                    <Plus size={14} className="mr-1" />
                                                    Add Location
                                                </Button>
                                            </div>

                                            {watch(`sites.${siteIndex}.locations`)?.map((location, locationIndex) => (
                                                <div key={locationIndex} className="bg-gray-50 dark:bg-gray-700 rounded p-3 mb-2">
                                                    <div className="flex justify-between items-center mb-2">
                                                        <span className="font-medium">
                                                            Location {locationIndex + 1}: {watch(`sites.${siteIndex}.locations.${locationIndex}.title`) || 'Untitled'}
                                                        </span>
                                                        <Button
                                                            type="button"
                                                            onClick={() => removeLocationFromSite(siteIndex, locationIndex)}
                                                            variant="ghost"
                                                            size="sm"
                                                            className="text-red-500 hover:text-red-700 h-6 w-6 p-0"
                                                        >
                                                            <X size={14} />
                                                        </Button>
                                                    </div>
                                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                                                        <Controller
                                                            name={`sites.${siteIndex}.locations.${locationIndex}.title`}
                                                            control={control}
                                                            render={({ field }) => (
                                                                <input
                                                                    type="text"
                                                                    value={field.value || ''}
                                                                    onChange={field.onChange}
                                                                    placeholder="Location title"
                                                                    className="px-2 py-1 border rounded text-sm dark:bg-gray-600"
                                                                />
                                                            )}
                                                        />
                                                        <Controller
                                                            name={`sites.${siteIndex}.locations.${locationIndex}.description`}
                                                            control={control}
                                                            render={({ field }) => (
                                                                <input
                                                                    type="text"
                                                                    value={field.value || ''}
                                                                    onChange={field.onChange}
                                                                    placeholder="Description"
                                                                    className="px-2 py-1 border rounded text-sm dark:bg-gray-600"
                                                                />
                                                            )}
                                                        />
                                                        <div className="flex gap-2">
                                                            <Controller
                                                                name={`sites.${siteIndex}.locations.${locationIndex}.latitude`}
                                                                control={control}
                                                                render={({ field }) => (
                                                                    <input
                                                                        type="number"
                                                                        step="any"
                                                                        value={field.value?.toString() || ''}
                                                                        onChange={(e) => field.onChange(parseFloat(e.target.value) || 0)}
                                                                        placeholder="Lat"
                                                                        className="px-2 py-1 border rounded text-sm w-full dark:bg-gray-600"
                                                                    />
                                                                )}
                                                            />
                                                            <Controller
                                                                name={`sites.${siteIndex}.locations.${locationIndex}.longitude`}
                                                                control={control}
                                                                render={({ field }) => (
                                                                    <input
                                                                        type="number"
                                                                        step="any"
                                                                        value={field.value?.toString() || ''}
                                                                        onChange={(e) => field.onChange(parseFloat(e.target.value) || 0)}
                                                                        placeholder="Lng"
                                                                        className="px-2 py-1 border rounded text-sm w-full dark:bg-gray-600"
                                                                    />
                                                                )}
                                                            />
                                                        </div>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {step === 4 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <FileText size={20} />
                                Documents & Final Details
                            </h3>

                            {/* Client Document Types */}
                            <div className="mb-6">
                                <label className="block text-sm font-medium mb-3">Client Required Documents</label>
                                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                                    {CLIENT_DOCUMENT_TYPES.map((docType) => (
                                        <label key={docType.id} className="flex items-center gap-2 p-3 border rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer">
                                            <input
                                                type="checkbox"
                                                checked={selectedDocumentTypes.includes(docType.id)}
                                                onChange={() => handleDocumentTypeChange(docType.id)}
                                                className="rounded"
                                            />
                                            <span className="text-sm">
                                                {docType.name}
                                                {docType.required && <span className="text-red-500 ml-1">*</span>}
                                            </span>
                                        </label>
                                    ))}
                                </div>
                            </div>

                            {/* Media Categories */}
                            <div className="mb-6">
                                <label className="block text-sm font-medium mb-3">Media Categories (Optional)</label>
                                <Controller
                                    name="media_categories"
                                    control={control}
                                    render={({ field }) => (
                                        <Textarea
                                            {...field}
                                            placeholder="Enter media categories separated by commas (e.g., company_logo, office_photos, team_photos, certificates)"
                                            className="w-full h-20 resize-none dark:bg-gray-700 dark:border-gray-600"
                                            value={Array.isArray(field.value) ? field.value.join(', ') : field.value || ''}
                                            onChange={(e) => {
                                                const value = e.target.value
                                                    .split(',')
                                                    .map(item => item.trim())
                                                    .filter(item => item.length > 0)
                                                field.onChange(value)
                                            }}
                                        />
                                    )}
                                />
                                <p className="text-xs text-gray-500 mt-1">
                                    Separate categories with commas. These will be used for organizing uploaded media files.
                                </p>
                            </div>

                            {/* File Upload Section */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                                {/* Profile Photo */}
                                <div className="border-2 border-dashed border-gray-300 rounded-xl p-6 dark:border-gray-600">
                                    <div className="flex flex-col items-center">
                                        <div className="relative mb-4">
                                            <input
                                                type="file"
                                                id="profileImage"
                                                onChange={handleProfileImageUpload}
                                                className="hidden"
                                                accept="image/*"
                                            />
                                            <label htmlFor="profileImage" className="cursor-pointer">
                                                <div className="relative w-32 h-32 rounded-full border-2 border-dashed border-gray-300 flex flex-col items-center justify-center bg-white hover:border-gray-400 transition dark:bg-gray-800">
                                                    {profileImage ? (
                                                        <>
                                                            <Image
                                                                src={URL.createObjectURL(profileImage)}
                                                                alt="Profile preview"
                                                                width={128}
                                                                height={128}
                                                                className="rounded-full object-cover w-full h-full"
                                                            />
                                                            <div className="absolute inset-0 bg-black bg-opacity-50 rounded-full flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
                                                                <Plus className="w-8 h-8 text-white" />
                                                            </div>
                                                        </>
                                                    ) : (
                                                        <>
                                                            <Plus className="w-8 h-8 text-gray-400 mb-2" />
                                                            <p className="text-sm text-gray-600 dark:text-gray-400 text-center">
                                                                Company Logo
                                                            </p>
                                                        </>
                                                    )}
                                                </div>
                                            </label>
                                        </div>
                                        <p className="text-sm text-gray-500 dark:text-gray-400 text-center">
                                            Upload company logo or profile photo
                                        </p>
                                    </div>
                                </div>

                                {/* Documents Upload */}
                                <div className="border-2 border-dashed border-gray-300 rounded-xl p-6 dark:border-gray-600">
                                    <div className="flex flex-col items-center">
                                        <UploadCloud className="w-12 h-12 text-gray-400 mb-3" />
                                        <p className="text-gray-600 dark:text-gray-300 font-medium text-center mb-3">
                                            Upload Client Documents
                                        </p>
                                        <input
                                            type="file"
                                            id="documents"
                                            multiple
                                            onChange={handleDocumentUpload}
                                            className="hidden"
                                            accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"
                                        />
                                        <label htmlFor="documents" className="cursor-pointer">
                                            <Button type="button" variant="outline">
                                                Select Files
                                            </Button>
                                        </label>

                                        {documents.length > 0 && (
                                            <div className="mt-4 w-full">
                                                <p className="text-sm font-medium mb-2">Selected files:</p>
                                                <div className="space-y-2 max-h-40 overflow-y-auto">
                                                    {documents.map((doc, index) => (
                                                        <div key={index} className="flex items-center justify-between bg-gray-50 dark:bg-gray-800 p-2 rounded">
                                                            <div className="flex items-center gap-2">
                                                                <FileText size={14} className="text-gray-500" />
                                                                <span className="text-sm truncate max-w-[200px] dark:text-gray-300">
                                                                    {doc.name}
                                                                </span>
                                                            </div>
                                                            <button
                                                                type="button"
                                                                onClick={() => removeDocument(index)}
                                                                className="text-red-500 hover:text-red-700"
                                                            >
                                                                <X size={16} />
                                                            </button>
                                                        </div>
                                                    ))}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* Status */}
                            <div className="mb-6">
                                <label className="flex items-center gap-2">
                                    <input
                                        type="checkbox"
                                        {...register("is_active")}
                                        defaultChecked={true}
                                        className="rounded"
                                    />
                                    <span>Set as Active Client</span>
                                </label>
                            </div>
                        </div>
                    )}

                    {/* Navigation Buttons */}
                    <div className="flex justify-between items-center pt-6 border-t dark:border-gray-700">
                        {step > 1 ? (
                            <Button
                                type="button"
                                variant="outline"
                                onClick={prevStep}
                            >
                                ← Back
                            </Button>
                        ) : (
                            <DialogClose asChild>
                                <Button
                                    type="button"
                                    variant="outline"
                                    onClick={handleCancel}
                                    className="dark:border-red-600"
                                >
                                    Cancel
                                </Button>
                            </DialogClose>
                        )}

                        {step < 4 ? (
                            <Button
                                type="button"
                                onClick={nextStep}
                            >
                                Next Step →
                            </Button>
                        ) : (
                            <div className="flex gap-2">
                                <DialogClose asChild>
                                    <Button
                                        type="button"
                                        variant="outline"
                                        onClick={handleCancel}
                                        className="dark:border-red-600"
                                    >
                                        Cancel
                                    </Button>
                                </DialogClose>
                                <Button
                                    type="submit"
                                    disabled={isSubmitting}
                                    className="bg-green-600 hover:bg-green-700"
                                >
                                    {isSubmitting ? (
                                        <>
                                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                                            Creating Client...
                                        </>
                                    ) : (
                                        'Create Client'
                                    )}
                                </Button>
                            </div>
                        )}
                    </div>
                </form>
            </DialogContent>
        </Dialog>
    )
}