'use client'
import {
    Dialog,
    DialogContent,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { ReactNode, useState, useEffect, useRef } from 'react'
import Image from "next/image"
import { FloatingLabelInput } from "../ui/floating-input"
import { FloatingLabelSelect } from "../ui/floating-select"
import { Textarea } from "../ui/textarea"
import { Plus, UploadCloud, X, User, Briefcase, FileText, Copy } from "lucide-react"
import { useForm, Controller } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { useAppDispatch } from "@/hooks/useAppDispatch"
import { createGuard, fetchGuards } from "@/store/slices/guardSlice"
import SweetAlertService from "@/lib/sweetAlert"
import { guardBasicSchema, GuardFormData } from "@/lib/validation/guard.schema"
import {
    COUNTRIES,
    BLOOD_GROUPS,
    MARITAL_STATUS,
    DOCUMENT_TYPES
} from "@/lib/validation/guard.types"
import { DialogTitle } from "@radix-ui/react-dialog"

interface GuardCreateFormProps {
    trigger: ReactNode
    isOpen?: boolean
    onOpenChange?: (open: boolean) => void
    onSuccess?: () => void
    guardTypes?: Array<{ id: number; name: string }>
    lastGuardCode?: string // Optional: last guard code from API
}

export function GuardCreateForm({
    trigger,
    isOpen,
    onOpenChange,
    onSuccess,
    guardTypes = [],
    lastGuardCode
}: GuardCreateFormProps) {
    const dispatch = useAppDispatch()
    const [isSubmitting, setIsSubmitting] = useState(false)
    const [profileImage, setProfileImage] = useState<File | null>(null)
    const [documents, setDocuments] = useState<File[]>([])
    const [selectedDocumentTypes, setSelectedDocumentTypes] = useState<string[]>([])
    const [languages, setLanguages] = useState<string[]>([])
    const [currentLanguage, setCurrentLanguage] = useState("")
    const [step, setStep] = useState(1)
    const [autoGeneratedCode, setAutoGeneratedCode] = useState<string>("")
    const [isGeneratingCode, setIsGeneratingCode] = useState(false)
    const guardCodeRef = useRef<HTMLInputElement>(null)

    const {
        control,
        register,
        handleSubmit,
        formState: { errors },
        reset,
        watch,
        setValue,
        trigger: triggerValidation,
        clearErrors,
    } = useForm<GuardFormData>({
        resolver: zodResolver(guardBasicSchema),
        defaultValues: {
            is_active: true,
            gender: "male",
            guard_code: "",
            full_name: "",
            phone: "",
            email: "",
            employee_company_card_number: "",
            driver_license: "",
            date_of_birth: "",
            country: "",
            city: "",
            address: "",
            zip_code: "",
            joining_date: "",
            license_expiry_date: "",
            issuing_source: "",
            password: "",
            guard_type_id: undefined,
            contract_id: undefined,
            document_types: [],
            profile_data: {
                marital_status: "single",
                has_work_permit: false,
                has_security_training: false,
                languages: [],
                place_of_birth: "",
                country_of_origin: "",
                current_country: "",
                current_city: "",
                current_address: "",
                citizenship: "",
                visa_countries: [],
                visa_expiry_date: "",
                father_name: "",
                mother_name: "",
                national_id_number: "",
                height: "",
                weight: "",
                blood_group: "",
                experience_years: 0,
                skills: "",
                highest_education_level: "",
                education_field: "",
                institution_name: "",
                graduation_year: undefined,
                emergency_contact_name: "",
                emergency_contact_phone: "",
                emergency_contact_relation: "",
                notes: "",
            },
        },
        mode: "onChange",
    })

    // Function to generate guard code in format: GD-YYYY-XXX
    const generateGuardCode = async (): Promise<string> => {
        try {
            setIsGeneratingCode(true)

            // Get current year
            const currentYear = new Date().getFullYear()

            // If we have lastGuardCode from props, use it to generate next number
            let nextNumber = 1

            if (lastGuardCode) {
                // Parse last code format: GD-YYYY-XXX
                const match = lastGuardCode.match(/GD-(\d{4})-(\d+)/)
                if (match && match[2]) {
                    nextNumber = parseInt(match[2]) + 1
                }
            } else {
                // Try to fetch guards to get the last code
                try {
                    const result = await dispatch(fetchGuards({ page: 1, per_page: 1 }))
                    if (fetchGuards.fulfilled.match(result)) {
                        const guards = result.payload.items
                        if (guards.length > 0) {
                            // Sort guards by ID to get the last one
                            const sortedGuards = [...guards].sort((a, b) => b.id - a.id)
                            const lastGuard = sortedGuards[0]

                            if (lastGuard.guard_code) {
                                const match = lastGuard.guard_code.match(/GD-(\d{4})-(\d+)/)
                                if (match && match[2]) {
                                    nextNumber = parseInt(match[2]) + 1
                                }
                            }
                        }
                    }
                } catch (error) {
                    console.warn("Could not fetch guards for code generation:", error)
                }
            }

            // Format number with leading zeros (001, 002, etc.)
            const formattedNumber = nextNumber.toString().padStart(3, '0')

            // Return formatted code
            return `GD-${currentYear}-${formattedNumber}`
        } catch (error) {
            console.error("Error generating guard code:", error)
            // Fallback: generate a random code
            const currentYear = new Date().getFullYear()
            const randomNum = Math.floor(Math.random() * 900) + 100 // 100-999
            return `GD-${currentYear}-${randomNum}`
        } finally {
            setIsGeneratingCode(false)
        }
    }

    // Initialize form with generated guard code when dialog opens
    useEffect(() => {
        const initializeForm = async () => {
            if (isOpen) {
                const generatedCode = await generateGuardCode()
                setAutoGeneratedCode(generatedCode)
                setValue("guard_code", generatedCode)
            }
        }

        initializeForm()
    }, [isOpen, setValue, lastGuardCode])

    // Copy guard code to clipboard
    const copyGuardCode = () => {
        if (guardCodeRef.current) {
            guardCodeRef.current.select()
            navigator.clipboard.writeText(autoGeneratedCode)
            SweetAlertService.success(
                "Copied!",
                "Guard code copied to clipboard.",
                {
                    timer: 1500,
                    showConfirmButton: false,
                }
            )
        }
    }

    // Regenerate guard code
    const regenerateGuardCode = async () => {
        const newCode = await generateGuardCode()
        setAutoGeneratedCode(newCode)
        setValue("guard_code", newCode)

        SweetAlertService.info(
            "Code Regenerated",
            "New guard code has been generated.",
            {
                timer: 1500,
                showConfirmButton: false,
            }
        )
    }

    const handleProfileImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            if (!file.type.startsWith('image/')) {
                SweetAlertService.error("Invalid file type", "Please upload an image file")
                return
            }
            if (file.size > 5 * 1024 * 1024) {
                SweetAlertService.error("File too large", "Please upload an image smaller than 5MB")
                return
            }
            setProfileImage(file)
        }
    }

    const handleDocumentUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const files = Array.from(e.target.files || [])
        const validFiles = files.filter(file => {
            const validTypes = [
                'application/pdf',
                'image/jpeg',
                'image/png',
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            ]
            return validTypes.includes(file.type) && file.size <= 10 * 1024 * 1024
        })

        if (validFiles.length !== files.length) {
            SweetAlertService.warning("Some files were skipped", "Only PDF, JPG, PNG, and DOC files up to 10MB are allowed")
        }

        setDocuments(prev => [...prev, ...validFiles])
    }

    const removeDocument = (index: number) => {
        setDocuments(prev => prev.filter((_, i) => i !== index))
    }

    const handleDocumentTypeChange = (docType: string) => {
        const newSelectedTypes = selectedDocumentTypes.includes(docType)
            ? selectedDocumentTypes.filter(type => type !== docType)
            : [...selectedDocumentTypes, docType]

        setSelectedDocumentTypes(newSelectedTypes)
        setValue("document_types", newSelectedTypes, { shouldValidate: true })
    }

    const addLanguage = () => {
        if (currentLanguage.trim() && !languages.includes(currentLanguage.trim())) {
            const updatedLanguages = [...languages, currentLanguage.trim()]
            setLanguages(updatedLanguages)
            setValue("profile_data.languages", updatedLanguages, { shouldValidate: true })
            setCurrentLanguage("")
        }
    }

    const removeLanguage = (language: string) => {
        const updatedLanguages = languages.filter(l => l !== language)
        setLanguages(updatedLanguages)
        setValue("profile_data.languages", updatedLanguages, { shouldValidate: true })
    }

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter') {
            e.preventDefault()
            addLanguage()
        }
    }

    const onSubmit = async (data: GuardFormData) => {
        setIsSubmitting(true);

        try {
            // Create FormData
            const formData = new FormData();

            // Use auto-generated code if guard_code is empty
            const finalGuardCode = autoGeneratedCode || data.guard_code;

            if (!finalGuardCode) {
                throw new Error("Guard code is required");
            }

            // Append all required fields first
            formData.append('guard_code', finalGuardCode);
            formData.append('full_name', data.full_name);
            formData.append('phone', data.phone);
            formData.append('employee_company_card_number', data.employee_company_card_number);
            formData.append('gender', data.gender);
            formData.append('country', data.country);
            formData.append('city', data.city);
            formData.append('joining_date', data.joining_date);

            // Append optional fields only if they have values
            if (data.email) formData.append('email', data.email);
            if (data.password) formData.append('password', data.password);
            if (data.driver_license) formData.append('driver_license', data.driver_license);
            if (data.date_of_birth) formData.append('date_of_birth', data.date_of_birth);
            if (data.address) formData.append('address', data.address);
            if (data.zip_code) formData.append('zip_code', data.zip_code);
            if (data.license_expiry_date) formData.append('license_expiry_date', data.license_expiry_date);
            if (data.issuing_source) formData.append('issuing_source', data.issuing_source);
            if (data.guard_type_id) formData.append('guard_type_id', data.guard_type_id.toString());
            if (data.contract_id) formData.append('contract_id', data.contract_id.toString());

            // Append status
            formData.append('is_active', data.is_active ? '1' : '0');

            // Append profile data if it exists
            if (data.profile_data) {
                // Convert boolean values to strings
                const profileData = {
                    ...data.profile_data,
                    has_work_permit: data.profile_data.has_work_permit ? 1 : 0,
                    has_security_training: data.profile_data.has_security_training ? 1 : 0,
                };
                formData.append('profile_data', JSON.stringify(profileData));
            }

            // Append document types
            if (data.document_types && data.document_types.length > 0) {
                formData.append('document_types', JSON.stringify(data.document_types));
            }

            // Append files
            if (profileImage) {
                formData.append('profile_image', profileImage);
            }

            if (documents.length > 0) {
                documents.forEach((doc, index) => {
                    formData.append(`documents[${index}]`, doc);
                });
            }

            // Dispatch create guard action
            const result = await dispatch(createGuard(formData));

            if (createGuard.fulfilled.match(result)) {
                SweetAlertService.success(
                    'Guard Created Successfully',
                    `${data.full_name} has been created with code: ${finalGuardCode}`,
                    {
                        timer: 2000,
                        showConfirmButton: false,
                    }
                );

                // Reset form
                reset();
                setProfileImage(null);
                setDocuments([]);
                setSelectedDocumentTypes([]);
                setLanguages([]);
                setCurrentLanguage("");
                setStep(1);
                clearErrors();

                // Generate new code for next guard
                const newCode = await generateGuardCode();
                setAutoGeneratedCode(newCode);
                setValue("guard_code", newCode);

                // Refresh guards list
                dispatch(fetchGuards({
                    page: 1,
                    per_page: 10,
                    sort_by: 'created_at',
                    sort_order: 'desc'
                }));

                // Call success callback
                if (onSuccess) onSuccess();
                if (onOpenChange) onOpenChange(false);
            } else {
                throw new Error(result.payload as string || 'Failed to create guard');
            }
        } catch (error) {
            SweetAlertService.error(
                'Creation Failed',
                error instanceof Error ? error.message : 'There was an error creating the guard. Please try again.'
            );
            console.error('Error creating guard:', error);
        } finally {
            setIsSubmitting(false);
        }
    };

    const validateStep = async (currentStep: number): Promise<boolean> => {
        let fieldsToValidate: (keyof GuardFormData)[] = []

        if (currentStep === 1) {
            fieldsToValidate = [
                'full_name', 'phone', 'gender',
                'employee_company_card_number', 'country', 'city'
            ] as (keyof GuardFormData)[]
        } else if (currentStep === 2) {
            fieldsToValidate = ['joining_date'] as (keyof GuardFormData)[]
        }

        const result = await triggerValidation(fieldsToValidate, { shouldFocus: true })
        return result
    }

    const nextStep = async () => {
        const isValid = await validateStep(step)
        if (isValid) {
            setStep(step + 1)
        } else {
            // Store the promise but don't await it immediately
            const alertPromise = SweetAlertService.warning(
                'Incomplete Information',
                'Please fill in all required fields correctly before proceeding.',
                {
                    timer: 3000,
                    showConfirmButton: true,
                    confirmButtonText: 'OK',
                    didClose: () => {
                        // Focus on the first error field after the alert closes
                        const firstErrorKey = Object.keys(errors)[0]
                        if (firstErrorKey) {
                            const element = document.querySelector(`[name="${firstErrorKey}"]`)
                            if (element) {
                                (element as HTMLElement).focus()
                            }
                        }
                    }
                }
            )

            // You can optionally await the promise if you need to do something after the alert
            await alertPromise;
        }
    }

    const prevStep = () => {
        setStep(step - 1)
    }

    const getCurrentDate = () => {
        const today = new Date()
        return today.toISOString().split('T')[0]
    }

    const getMinDate = () => {
        const minDate = new Date()
        minDate.setFullYear(minDate.getFullYear() - 100)
        return minDate.toISOString().split('T')[0]
    }

    return (
        <Dialog open={isOpen} onOpenChange={onOpenChange}>
            <DialogTrigger asChild>
                {trigger}
            </DialogTrigger>

            <DialogContent className="sm:max-w-[1200px] w-[95vw] max-w-[95vw] mx-auto max-h-[90vh] overflow-y-auto dark:bg-gray-900 p-4 sm:p-6">
                <DialogTitle></DialogTitle>

                {/* Header */}
                <div className="flex items-center gap-2 text-lg font-semibold mb-6">
                    <Image src="/images/logo.png" alt="Logo" width={24} height={24} />
                    <span className="whitespace-nowrap">Add New Guard</span>
                </div>

                {/* Validation Errors Debug */}
                {Object.keys(errors).length > 0 && (
                    <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-md">
                        <p className="text-sm font-medium text-red-800">Validation Errors:</p>
                        <ul className="mt-1 text-sm text-red-600">
                            {Object.entries(errors).map(([key, error]) => (
                                <li key={key}>
                                    {key}: {error?.message || 'Invalid'}
                                </li>
                            ))}
                        </ul>
                    </div>
                )}

                {/* Progress Steps */}
                <div className="flex items-center justify-center mb-6">
                    <div className="flex items-center space-x-2">
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 1 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                            <User size={20} />
                        </div>
                        <div className={`w-16 h-1 ${step >= 2 ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 2 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                            <Briefcase size={20} />
                        </div>
                        <div className={`w-16 h-1 ${step >= 3 ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 3 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                            <FileText size={20} />
                        </div>
                    </div>
                </div>

                <form onSubmit={handleSubmit(onSubmit)}>
                    {step === 1 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <User size={20} />
                                Basic Information
                            </h3>

                            {/* Guard Code Section */}
                            <div className="mb-6 bg-blue-50 dark:bg-gray-800 rounded-lg p-4">
                                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                                    <div>
                                        <h4 className="font-semibold text-gray-700 dark:text-gray-300">
                                            Guard Code
                                        </h4>
                                        <p className="text-sm text-gray-600 dark:text-gray-400">
                                            This code is automatically generated
                                        </p>
                                    </div>

                                    <div className="flex items-center gap-2">
                                        <div className="relative">
                                            <input
                                                ref={guardCodeRef}
                                                type="text"
                                                value={autoGeneratedCode}
                                                readOnly
                                                className="w-full px-4 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg font-mono text-lg font-bold text-center"
                                            />
                                            {isGeneratingCode && (
                                                <div className="absolute inset-0 flex items-center justify-center bg-white bg-opacity-80">
                                                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600"></div>
                                                </div>
                                            )}
                                        </div>

                                        <div className="flex gap-1">
                                            <Button
                                                type="button"
                                                size="sm"
                                                variant="outline"
                                                onClick={copyGuardCode}
                                                className="h-9"
                                            >
                                                <Copy size={16} />
                                            </Button>
                                            <Button
                                                type="button"
                                                size="sm"
                                                variant="outline"
                                                onClick={regenerateGuardCode}
                                                disabled={isGeneratingCode}
                                                className="h-9"
                                            >
                                                Regenerate
                                            </Button>
                                        </div>
                                    </div>
                                </div>

                                {/* Hidden input for form submission */}
                                <input
                                    type="hidden"
                                    {...register("guard_code")}
                                    value={autoGeneratedCode}
                                    onChange={() => { }}
                                />
                            </div>

                            {/* First Row */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                {/* Full Name */}
                                <div>
                                    <Controller
                                        name="full_name"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Full Name *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.full_name?.message}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Phone Number */}
                                <div>
                                    <Controller
                                        name="phone"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Phone Number *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                type="tel"
                                                error={errors.phone?.message}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Email */}
                                <div>
                                    <Controller
                                        name="email"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Email"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                type="email"
                                                error={errors.email?.message}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Gender */}
                                <div>
                                    <Controller
                                        name="gender"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Gender *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.gender?.message}
                                            >
                                                <option value="">Select...</option>
                                                <option value="male">Male</option>
                                                <option value="female">Female</option>
                                                <option value="other">Other</option>
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Second Row */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                {/* Employee Card Number */}
                                <div>
                                    <Controller
                                        name="employee_company_card_number"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Employee Card Number *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.employee_company_card_number?.message}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Driver License */}
                                <div>
                                    <Controller
                                        name="driver_license"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Driver License"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Date of Birth */}
                                <div>
                                    <Controller
                                        name="date_of_birth"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Date of Birth"
                                                type="date"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                max={getCurrentDate()}
                                                min={getMinDate()}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Country */}
                                <div>
                                    <Controller
                                        name="country"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Country *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.country?.message}
                                            >
                                                <option value="">Select...</option>
                                                {COUNTRIES.map(country => (
                                                    <option key={country.code} value={country.name}>
                                                        {country.name}
                                                    </option>
                                                ))}
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Third Row */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                {/* City */}
                                <div>
                                    <Controller
                                        name="city"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="City *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.city?.message}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Address */}
                                <div className="md:col-span-2">
                                    <Controller
                                        name="address"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Address"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Zip Code */}
                                <div>
                                    <Controller
                                        name="zip_code"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Zip Code"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            />
                                        )}
                                    />
                                </div>
                            </div>
                        </div>
                    )}

                    {step === 2 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <Briefcase size={20} />
                                Guard Information
                            </h3>

                            {/* First Row */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                {/* Joining Date */}
                                <div>
                                    <Controller
                                        name="joining_date"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Joining Date *"
                                                type="date"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                max={getCurrentDate()}
                                                error={errors.joining_date?.message}
                                            />
                                        )}
                                    />
                                </div>

                                {/* License Expiry Date */}
                                <div>
                                    <Controller
                                        name="license_expiry_date"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="License Expiry Date"
                                                type="date"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                min={getCurrentDate()}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Issuing Source */}
                                <div>
                                    <Controller
                                        name="issuing_source"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Issuing Source"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            >
                                                <option value="">Select...</option>
                                                <option value="state">State</option>
                                                <option value="federal">Federal</option>
                                                <option value="private">Private</option>
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>

                                {/* Guard Type */}
                                <div>
                                    <Controller
                                        name="guard_type_id"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Guard Type"
                                                value={field.value?.toString() || ''}
                                                onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : null)}
                                                error={errors.guard_type_id?.message}
                                            >
                                                <option value="">Select...</option>
                                                {guardTypes.map(type => (
                                                    <option key={type.id} value={type.id}>
                                                        {type.name}
                                                    </option>
                                                ))}
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Password */}
                            <div className="mb-6">
                                <Controller
                                    name="password"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Password (for system access)"
                                            type="password"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            placeholder="Min. 6 characters"
                                            error={errors.password?.message}
                                        />
                                    )}
                                />
                            </div>

                            {/* Profile Data Section */}
                            <div className="bg-blue-50 dark:bg-gray-800 rounded-lg p-6 mb-6">
                                <h4 className="font-semibold mb-4">Profile Details</h4>

                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                    {/* Height */}
                                    <div>
                                        <Controller
                                            name="profile_data.height"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelInput
                                                    label="Height (cm)"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                />
                                            )}
                                        />
                                    </div>

                                    {/* Weight */}
                                    <div>
                                        <Controller
                                            name="profile_data.weight"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelInput
                                                    label="Weight (kg)"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                />
                                            )}
                                        />
                                    </div>

                                    {/* Blood Group */}
                                    <div>
                                        <Controller
                                            name="profile_data.blood_group"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelSelect
                                                    label="Blood Group"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                >
                                                    <option value="">Select...</option>
                                                    {BLOOD_GROUPS.map(group => (
                                                        <option key={group} value={group}>{group}</option>
                                                    ))}
                                                </FloatingLabelSelect>
                                            )}
                                        />
                                    </div>

                                    {/* Marital Status */}
                                    <div>
                                        <Controller
                                            name="profile_data.marital_status"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelSelect
                                                    label="Marital Status"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                >
                                                    <option value="">Select...</option>
                                                    {MARITAL_STATUS.map(status => (
                                                        <option key={status} value={status}>
                                                            {status.charAt(0).toUpperCase() + status.slice(1)}
                                                        </option>
                                                    ))}
                                                </FloatingLabelSelect>
                                            )}
                                        />
                                    </div>
                                </div>

                                {/* Languages */}
                                <div className="mb-6">
                                    <label className="block text-sm font-medium mb-2">Languages</label>
                                    <div className="flex gap-2 mb-2">
                                        <input
                                            type="text"
                                            value={currentLanguage}
                                            onChange={(e) => setCurrentLanguage(e.target.value)}
                                            onKeyDown={handleKeyDown}
                                            placeholder="Type language and press Enter"
                                            className="flex-1 px-3 py-2 border rounded-md dark:bg-gray-700 dark:border-gray-600"
                                        />
                                        <Button
                                            type="button"
                                            onClick={addLanguage}
                                            variant="outline"
                                        >
                                            <Plus size={16} />
                                        </Button>
                                    </div>

                                    {languages.length > 0 && (
                                        <div className="flex flex-wrap gap-2">
                                            {languages.map((language, index) => (
                                                <div key={index} className="flex items-center gap-1 bg-blue-100 text-blue-800 px-3 py-1 rounded-full">
                                                    {language}
                                                    <button
                                                        type="button"
                                                        onClick={() => removeLanguage(language)}
                                                        className="text-blue-600 hover:text-blue-800"
                                                    >
                                                        <X size={14} />
                                                    </button>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </div>

                                {/* Experience and Skills */}
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                                    {/* Experience Years */}
                                    <div>
                                        <Controller
                                            name="profile_data.experience_years"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelInput
                                                    label="Experience (years)"
                                                    type="number"
                                                    min="0"
                                                    value={field.value?.toString() || ''}
                                                    onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : 0)}
                                                />
                                            )}
                                        />
                                    </div>

                                    {/* Skills */}
                                    <div>
                                        <Controller
                                            name="profile_data.skills"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelInput
                                                    label="Skills"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                    placeholder="e.g., First Aid, Surveillance, Combat"
                                                />
                                            )}
                                        />
                                    </div>
                                </div>

                                {/* Checkboxes */}
                                <div className="flex gap-6 mb-6">
                                    <label className="flex items-center gap-2">
                                        <input
                                            type="checkbox"
                                            {...register("profile_data.has_work_permit")}
                                            className="rounded"
                                        />
                                        <span>Has Work Permit</span>
                                    </label>

                                    <label className="flex items-center gap-2">
                                        <input
                                            type="checkbox"
                                            {...register("profile_data.has_security_training")}
                                            className="rounded"
                                        />
                                        <span>Has Security Training</span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    )}

                    {step === 3 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <FileText size={20} />
                                Documents & Final Details
                            </h3>

                            {/* Document Types */}
                            <div className="mb-6">
                                <label className="block text-sm font-medium mb-3">Required Documents</label>
                                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                                    {DOCUMENT_TYPES.map((docType) => (
                                        <label key={docType.id} className="flex items-center gap-2 p-3 border rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer">
                                            <input
                                                type="checkbox"
                                                checked={selectedDocumentTypes.includes(docType.id)}
                                                onChange={() => handleDocumentTypeChange(docType.id)}
                                                className="rounded"
                                            />
                                            <span className="text-sm">
                                                {docType.name}
                                                {docType.required && <span className="text-red-500 ml-1">*</span>}
                                            </span>
                                        </label>
                                    ))}
                                </div>
                            </div>

                            {/* File Upload Section */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                                {/* Profile Photo */}
                                <div className="border-2 border-dashed border-gray-300 rounded-xl p-6">
                                    <div className="flex flex-col items-center">
                                        <div className="relative mb-4">
                                            <input
                                                type="file"
                                                id="profileImage"
                                                onChange={handleProfileImageUpload}
                                                className="hidden"
                                                accept="image/*"
                                            />
                                            <label htmlFor="profileImage" className="cursor-pointer">
                                                <div className="relative w-32 h-32 rounded-full border-2 border-dashed border-gray-300 flex flex-col items-center justify-center bg-white hover:border-gray-400 transition dark:bg-gray-800 dark:border-gray-600">
                                                    {profileImage ? (
                                                        <>
                                                            <Image
                                                                src={URL.createObjectURL(profileImage)}
                                                                alt="Profile preview"
                                                                width={128}
                                                                height={128}
                                                                className="rounded-full object-cover w-full h-full"
                                                            />
                                                            <div className="absolute inset-0 bg-black bg-opacity-50 rounded-full flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
                                                                <Plus className="w-8 h-8 text-white" />
                                                            </div>
                                                        </>
                                                    ) : (
                                                        <>
                                                            <Plus className="w-8 h-8 text-gray-400 mb-2" />
                                                            <p className="text-sm text-gray-600 dark:text-gray-400 text-center">
                                                                Profile Photo
                                                            </p>
                                                        </>
                                                    )}
                                                </div>
                                            </label>
                                        </div>
                                        <p className="text-sm text-gray-500 dark:text-gray-400 text-center">
                                            Upload a clear profile photo
                                        </p>
                                    </div>
                                </div>

                                {/* Documents Upload */}
                                <div className="border-2 border-dashed border-gray-300 rounded-xl p-6 dark:border-gray-600">
                                    <div className="flex flex-col items-center">
                                        <UploadCloud className="w-12 h-12 text-gray-400 mb-3" />
                                        <p className="text-gray-600 dark:text-gray-300 font-medium text-center mb-3">
                                            Upload Required Documents
                                        </p>
                                        <input
                                            type="file"
                                            id="documents"
                                            multiple
                                            onChange={handleDocumentUpload}
                                            className="hidden"
                                            accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"
                                        />
                                        <label htmlFor="documents" className="cursor-pointer">
                                            <Button type="button" variant="outline">
                                                Select Files
                                            </Button>
                                        </label>

                                        {documents.length > 0 && (
                                            <div className="mt-4 w-full">
                                                <p className="text-sm font-medium mb-2">Selected files:</p>
                                                <div className="space-y-2 max-h-40 overflow-y-auto">
                                                    {documents.map((doc, index) => (
                                                        <div key={index} className="flex items-center justify-between bg-gray-50 dark:bg-gray-800 p-2 rounded">
                                                            <div className="flex items-center gap-2">
                                                                <FileText size={14} className="text-gray-500" />
                                                                <span className="text-sm truncate max-w-[200px] dark:text-gray-300">
                                                                    {doc.name}
                                                                </span>
                                                            </div>
                                                            <button
                                                                type="button"
                                                                onClick={() => removeDocument(index)}
                                                                className="text-red-500 hover:text-red-700"
                                                            >
                                                                <X size={16} />
                                                            </button>
                                                        </div>
                                                    ))}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* Emergency Contact */}
                            <div className="bg-yellow-50 dark:bg-gray-800 rounded-lg p-6 mb-6">
                                <h4 className="font-semibold mb-4">Emergency Contact</h4>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                    <Controller
                                        name="profile_data.emergency_contact_name"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Contact Name"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            />
                                        )}
                                    />

                                    <Controller
                                        name="profile_data.emergency_contact_phone"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Contact Phone"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                type="tel"
                                            />
                                        )}
                                    />

                                    <Controller
                                        name="profile_data.emergency_contact_relation"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Relationship"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                placeholder="e.g., Spouse, Parent"
                                            />
                                        )}
                                    />
                                </div>
                            </div>

                            {/* Notes */}
                            <div className="mb-6">
                                <label className="block text-sm font-medium mb-2">Additional Notes</label>
                                <Controller
                                    name="profile_data.notes"
                                    control={control}
                                    render={({ field }) => (
                                        <Textarea
                                            {...field}
                                            placeholder="Any additional information..."
                                            className="w-full h-32 resize-none dark:bg-gray-700 dark:border-gray-600"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                        />
                                    )}
                                />
                            </div>

                            {/* Status */}
                            <div className="mb-6">
                                <label className="flex items-center gap-2">
                                    <input
                                        type="checkbox"
                                        {...register("is_active")}
                                        defaultChecked={true}
                                        className="rounded"
                                    />
                                    <span>Set as Active Guard</span>
                                </label>
                            </div>
                        </div>
                    )}

                    {/* Navigation Buttons */}
                    <div className="flex justify-between items-center pt-6 border-t dark:border-gray-700">
                        {step > 1 ? (
                            <Button
                                type="button"
                                variant="outline"
                                onClick={prevStep}
                            >
                                ← Back
                            </Button>
                        ) : (
                            <Button
                                type="button"
                                variant="outline"
                                onClick={() => onOpenChange && onOpenChange(false)}
                            >
                                Cancel
                            </Button>
                        )}

                        {step < 3 ? (
                            <Button
                                type="button"
                                onClick={nextStep}
                            >
                                Next Step →
                            </Button>
                        ) : (
                            <div className="flex gap-2">
                                <Button
                                    type="button"
                                    variant="outline"
                                    onClick={() => onOpenChange && onOpenChange(false)}
                                >
                                    Cancel
                                </Button>
                                <Button
                                    type="submit"
                                    disabled={isSubmitting}
                                    className="bg-green-600 hover:bg-green-700"
                                >
                                    {isSubmitting ? (
                                        <>
                                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                                            Creating...
                                        </>
                                    ) : (
                                        'Create Guard'
                                    )}
                                </Button>
                            </div>
                        )}
                    </div>
                </form>
            </DialogContent>
        </Dialog>
    )
}