'use client'
import {
    Dialog,
    DialogContent,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { ReactNode, useState, useEffect, useRef, useCallback } from 'react'
import Image from "next/image"
import { FloatingLabelInput } from "../ui/floating-input"
import { FloatingLabelSelect } from "../ui/floating-select"
import { Textarea } from "../ui/textarea"
import { Plus, UploadCloud, X, User, Briefcase, FileText, Copy, Loader2 } from "lucide-react"
import { useForm, Controller } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { useAppDispatch } from "@/hooks/useAppDispatch"
import { useAppSelector } from "@/hooks/useAppSelector"
import { createGuard, fetchGuards } from "@/store/slices/guardSlice"
import { fetchGuardTypes } from "@/store/slices/guardTypeSlice"
import SweetAlertService from "@/lib/sweetAlert"
import { guardBasicSchema, GuardFormData } from "@/lib/validation/guard.schema"
import {
    COUNTRIES,
    BLOOD_GROUPS,
    MARITAL_STATUS,
    DOCUMENT_TYPES,
    US_STATES
} from "@/lib/validation/guard.types"
import { DialogTitle } from "@radix-ui/react-dialog"
import { GuardProfileData } from "@/app/types/guard"
import { z } from "zod"

// US ZIP code validation regex
const US_ZIP_REGEX = /^\d{5}(-\d{4})?$/

interface GuardCreateFormProps {
    trigger: ReactNode
    isOpen?: boolean
    onOpenChange?: (open: boolean) => void
    onSuccess?: () => void
    lastGuardCode?: string
}

export function GuardCreateForm({
    trigger,
    isOpen,
    onOpenChange,
    onSuccess,
    lastGuardCode
}: GuardCreateFormProps) {
    const dispatch = useAppDispatch()
    const [isSubmitting, setIsSubmitting] = useState(false)
    const [profileImage, setProfileImage] = useState<File | null>(null)
    const [documents, setDocuments] = useState<File[]>([])
    const [selectedDocumentTypes, setSelectedDocumentTypes] = useState<string[]>([])
    const [languages, setLanguages] = useState<string[]>([])
    const [currentLanguage, setCurrentLanguage] = useState("")
    const [visaCountries, setVisaCountries] = useState<string[]>([])
    const [currentVisaCountry, setCurrentVisaCountry] = useState("")
    const [step, setStep] = useState(1)
    const [autoGeneratedCode, setAutoGeneratedCode] = useState<string>("")
    const [isGeneratingCode, setIsGeneratingCode] = useState(false)
    const guardCodeRef = useRef<HTMLInputElement>(null)

    // Get officer types from Redux store
    const { guardTypes, isLoading: isLoadingGuardTypes } = useAppSelector((state) => state.guardTypes)

    // Fetch officer types when dialog opens
    useEffect(() => {
        dispatch(fetchGuardTypes({
            per_page: 100,
        }))
    }, [dispatch])

    const {
        control,
        register,
        handleSubmit,
        formState: { errors },
        reset,
        setValue,
        trigger: triggerValidation,
        clearErrors,
        watch,
    } = useForm<GuardFormData>({
        resolver: zodResolver(guardBasicSchema),
        defaultValues: {
            is_active: true,
            gender: "male",
            guard_code: "",
            full_name: "",
            phone: "",
            email: "",
            employee_company_card_number: "",
            driver_license: "",
            date_of_birth: "",
            country: "",
            city: "",
            address: "",
            zip_code: "",
            state: "",
            joining_date: "",
            license_expiry_date: "",
            issuing_source: "",
            password: "",
            guard_type_id: undefined,
            contract_id: undefined,
            document_types: [],
            profile_data: {
                marital_status: "single",
                has_work_permit: false,
                has_security_training: false,
                languages: [],
                place_of_birth: "",
                country_of_origin: "",
                current_country: "",
                current_city: "",
                current_address: "",
                current_state: "",
                current_zip_code: "",
                citizenship: "",
                visa_countries: [],
                visa_expiry_date: "",
                father_name: "",
                mother_name: "",
                national_id_number: "",
                height: "",
                weight: "",
                blood_group: "",
                experience_years: 0,
                skills: "",
                highest_education_level: "",
                education_field: "",
                institution_name: "",
                graduation_year: undefined,
                emergency_contact_name: "",
                emergency_contact_phone: "",
                emergency_contact_relation: "",
                notes: "",
            },
        },
        mode: "onChange",
    })

    // Handle dialog close
    const handleDialogClose = useCallback((open: boolean) => {
        if (!open && !isSubmitting) {
            resetForm()
        }
        onOpenChange?.(open)
    }, [onOpenChange, isSubmitting])

    // Reset form function
    const resetForm = useCallback(() => {
        reset()
        setProfileImage(null)
        setDocuments([])
        setSelectedDocumentTypes([])
        setLanguages([])
        setVisaCountries([])
        setCurrentLanguage("")
        setCurrentVisaCountry("")
        setStep(1)
        clearErrors()
    }, [reset, clearErrors])

    // Generate officer code
    const generateGuardCode = useCallback(async (): Promise<string> => {
        try {
            setIsGeneratingCode(true)
            const currentYear = new Date().getFullYear()
            let nextNumber = 1

            if (lastGuardCode) {
                const match = lastGuardCode.match(/GD-(\d{4})-(\d+)/)
                if (match?.[2]) {
                    nextNumber = parseInt(match[2]) + 1
                }
            } else {
                try {
                    const result = await dispatch(fetchGuards({ page: 1, per_page: 10 }))
                    if (fetchGuards.fulfilled.match(result)) {
                        const guards = result.payload.items
                        if (guards.length > 0) {
                            const sortedGuards = [...guards].sort((a, b) => b.id - a.id)
                            const lastGuard = sortedGuards[0]
                            if (lastGuard.guard_code) {
                                const match = lastGuard.guard_code.match(/GD-(\d{4})-(\d+)/)
                                if (match?.[2]) {
                                    nextNumber = parseInt(match[2]) + 1
                                }
                            }
                        }
                    }
                } catch (error) {
                    console.warn("Could not fetch guards for code generation:", error)
                }
            }

            const formattedNumber = nextNumber.toString().padStart(3, '0')
            return `GD-${currentYear}-${formattedNumber}`
        } catch (error) {
            console.error("Error generating officer code:", error)
            const currentYear = new Date().getFullYear()
            const randomNum = Math.floor(Math.random() * 900) + 100
            return `GD-${currentYear}-${randomNum}`
        } finally {
            setIsGeneratingCode(false)
        }
    }, [dispatch, lastGuardCode])

    // Initialize form
    useEffect(() => {
        const initializeForm = async () => {
            if (isOpen) {
                const generatedCode = await generateGuardCode()
                setAutoGeneratedCode(generatedCode)
                setValue("guard_code", generatedCode)
            }
        }

        initializeForm()
    }, [isOpen, setValue, generateGuardCode])

    const copyGuardCode = useCallback(() => {
        if (guardCodeRef.current) {
            guardCodeRef.current.select()
            navigator.clipboard.writeText(autoGeneratedCode)
            SweetAlertService.success(
                "Copied!",
                "Officer code copied to clipboard.",
                { timer: 1500, showConfirmButton: false }
            )
        }
    }, [autoGeneratedCode])

    const regenerateGuardCode = useCallback(async () => {
        const newCode = await generateGuardCode()
        setAutoGeneratedCode(newCode)
        setValue("guard_code", newCode)
        SweetAlertService.info(
            "Code Regenerated",
            "New officer code has been generated.",
            { timer: 1500, showConfirmButton: false }
        )
    }, [generateGuardCode, setValue])

    // File upload handlers
    const handleProfileImageUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            if (!file.type.startsWith('image/')) {
                SweetAlertService.error("Invalid file type", "Please upload an image file")
                return
            }
            if (file.size > 5 * 1024 * 1024) {
                SweetAlertService.error("File too large", "Please upload an image smaller than 5MB")
                return
            }
            setProfileImage(file)
        }
    }, [])

    const handleDocumentUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const files = Array.from(e.target.files || [])
        const validFiles = files.filter(file => {
            const validTypes = [
                'application/pdf',
                'image/jpeg',
                'image/png',
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            ]
            return validTypes.includes(file.type) && file.size <= 10 * 1024 * 1024
        })

        if (validFiles.length !== files.length) {
            SweetAlertService.warning("Some files were skipped", "Only PDF, JPG, PNG, and DOC files up to 10MB are allowed")
        }

        setDocuments(prev => [...prev, ...validFiles])
    }, [])

    const removeDocument = useCallback((index: number) => {
        setDocuments(prev => prev.filter((_, i) => i !== index))
    }, [])

    // Handle document type selection
    const handleDocumentTypeChange = useCallback((docType: string) => {
        const newSelectedTypes = selectedDocumentTypes.includes(docType)
            ? selectedDocumentTypes.filter(type => type !== docType)
            : [...selectedDocumentTypes, docType]

        setSelectedDocumentTypes(newSelectedTypes)
        setValue("document_types", newSelectedTypes, { shouldValidate: true })
    }, [selectedDocumentTypes, setValue])

    // Language handlers
    const addLanguage = useCallback(() => {
        if (currentLanguage.trim() && !languages.includes(currentLanguage.trim())) {
            const updatedLanguages = [...languages, currentLanguage.trim()]
            setLanguages(updatedLanguages)
            setValue("profile_data.languages", updatedLanguages, { shouldValidate: true })
            setCurrentLanguage("")
        }
    }, [currentLanguage, languages, setValue])

    const removeLanguage = useCallback((language: string) => {
        const updatedLanguages = languages.filter(l => l !== language)
        setLanguages(updatedLanguages)
        setValue("profile_data.languages", updatedLanguages, { shouldValidate: true })
    }, [languages, setValue])

    // Visa country handlers
    const addVisaCountry = useCallback(() => {
        if (currentVisaCountry.trim() && !visaCountries.includes(currentVisaCountry.trim())) {
            const updatedVisaCountries = [...visaCountries, currentVisaCountry.trim()]
            setVisaCountries(updatedVisaCountries)
            setValue("profile_data.visa_countries", updatedVisaCountries, { shouldValidate: true })
            setCurrentVisaCountry("")
        }
    }, [currentVisaCountry, visaCountries, setValue])

    const removeVisaCountry = useCallback((country: string) => {
        const updatedVisaCountries = visaCountries.filter(c => c !== country)
        setVisaCountries(updatedVisaCountries)
        setValue("profile_data.visa_countries", updatedVisaCountries, { shouldValidate: true })
    }, [visaCountries, setValue])

    const handleKeyDown = useCallback((e: React.KeyboardEvent, type: 'language' | 'visaCountry') => {
        if (e.key === 'Enter') {
            e.preventDefault()
            if (type === 'language') {
                addLanguage()
            } else {
                addVisaCountry()
            }
        }
    }, [addLanguage, addVisaCountry])

    // US ZIP code validation function
    const validateUSZipCode = useCallback((zipCode: string): boolean => {
        return US_ZIP_REGEX.test(zipCode)
    }, [])

    // Helper function to prepare profile data with proper typing
    const prepareProfileData = (data: GuardFormData['profile_data']): Partial<GuardProfileData> => {
        if (!data) return {}

        const profileData: Partial<GuardProfileData> = {}

        // Add only non-empty values with proper type checking
        if (data.place_of_birth && data.place_of_birth.trim() !== '') {
            profileData.place_of_birth = data.place_of_birth
        }
        if (data.country_of_origin && data.country_of_origin.trim() !== '') {
            profileData.country_of_origin = data.country_of_origin
        }
        if (data.current_country && data.current_country.trim() !== '') {
            profileData.current_country = data.current_country
        }
        if (data.current_state && data.current_state.trim() !== '') {
            profileData.current_state = data.current_state
        }
        if (data.current_city && data.current_city.trim() !== '') {
            profileData.current_city = data.current_city
        }
        if (data.current_address && data.current_address.trim() !== '') {
            profileData.current_address = data.current_address
        }
        if (data.current_zip_code && data.current_zip_code.trim() !== '') {
            profileData.current_zip_code = data.current_zip_code
        }
        if (data.citizenship && data.citizenship.trim() !== '') {
            profileData.citizenship = data.citizenship
        }

        if (data.visa_countries && data.visa_countries.length > 0) {
            profileData.visa_countries = data.visa_countries
        }
        if (data.visa_expiry_date && data.visa_expiry_date.trim() !== '') {
            profileData.visa_expiry_date = data.visa_expiry_date
        }

        if (data.father_name && data.father_name.trim() !== '') {
            profileData.father_name = data.father_name
        }
        if (data.mother_name && data.mother_name.trim() !== '') {
            profileData.mother_name = data.mother_name
        }
        if (data.national_id_number && data.national_id_number.trim() !== '') {
            profileData.national_id_number = data.national_id_number
        }

        if (data.marital_status) {
            profileData.marital_status = data.marital_status
        }
        if (data.height && data.height.trim() !== '') {
            profileData.height = data.height
        }
        if (data.weight && data.weight.trim() !== '') {
            profileData.weight = data.weight
        }
        if (data.blood_group && data.blood_group.trim() !== '') {
            profileData.blood_group = data.blood_group
        }

        if (data.experience_years && data.experience_years > 0) {
            profileData.experience_years = data.experience_years
        }
        if (data.skills && data.skills.trim() !== '') {
            profileData.skills = data.skills
        }

        if (data.languages && data.languages.length > 0) {
            profileData.languages = data.languages
        }

        if (data.highest_education_level && data.highest_education_level.trim() !== '') {
            profileData.highest_education_level = data.highest_education_level
        }
        if (data.education_field && data.education_field.trim() !== '') {
            profileData.education_field = data.education_field
        }
        if (data.institution_name && data.institution_name.trim() !== '') {
            profileData.institution_name = data.institution_name
        }
        if (data.graduation_year) {
            profileData.graduation_year = data.graduation_year
        }

        // Boolean fields (always include if they exist)
        if (data.has_work_permit !== undefined) {
            profileData.has_work_permit = data.has_work_permit ? 1 : 0
        }
        if (data.has_security_training !== undefined) {
            profileData.has_security_training = data.has_security_training ? 1 : 0
        }

        if (data.emergency_contact_name && data.emergency_contact_name.trim() !== '') {
            profileData.emergency_contact_name = data.emergency_contact_name
        }
        if (data.emergency_contact_phone && data.emergency_contact_phone.trim() !== '') {
            profileData.emergency_contact_phone = data.emergency_contact_phone
        }
        if (data.emergency_contact_relation && data.emergency_contact_relation.trim() !== '') {
            profileData.emergency_contact_relation = data.emergency_contact_relation
        }

        if (data.notes && data.notes.trim() !== '') {
            profileData.notes = data.notes
        }

        return profileData
    }

    // Submit handler with proper typing
    const onSubmit = async (data: GuardFormData) => {
        setIsSubmitting(true)

        try {
            const formData = new FormData()

            // Always include required fields
            const requiredFields: Record<string, string> = {
                guard_code: autoGeneratedCode || data.guard_code || '',
                full_name: data.full_name || '',
                phone: data.phone || '',
                employee_company_card_number: data.employee_company_card_number || '',
                gender: data.gender || 'male',
                country: data.country || '',
                address: data.address || '',
                city: data.city || '',
                state: data.state || '',
                zip_code: data.zip_code || '',
                joining_date: data.joining_date || '',
                is_active: data.is_active ? '1' : '0'
            }

            // Validate US ZIP codes
            if (data?.zip_code && !validateUSZipCode(data.zip_code)) {
                SweetAlertService.error(
                    "Invalid ZIP Code",
                    "Please enter a valid US ZIP code (e.g., 12345 or 12345-6789)"
                )
                setIsSubmitting(false)
                return
            }


            if (
                data?.profile_data?.current_zip_code &&
                !validateUSZipCode(data.profile_data.current_zip_code)
            ) {
                SweetAlertService.error(
                    "Invalid Current ZIP Code",
                    "Please enter a valid US ZIP code for current address (e.g., 12345 or 12345-6789)"
                )
                setIsSubmitting(false)
                return
            }

            // Append required fields
            Object.entries(requiredFields).forEach(([key, value]) => {
                if (value) formData.append(key, value)
            })

            // Append optional fields only if they have values
            const optionalFields: Record<string, string | number | undefined> = {
                email: data.email,
                password: data.password,
                driver_license: data.driver_license,
                date_of_birth: data.date_of_birth,
                license_expiry_date: data.license_expiry_date,
                issuing_source: data.issuing_source
            }

            Object.entries(optionalFields).forEach(([key, value]) => {
                if (value && value.toString().trim() !== '') {
                    formData.append(key, value.toString())
                }
            })

            // Append numeric fields
            if (data.guard_type_id) {
                formData.append('guard_type_id', data.guard_type_id.toString())
            }
            if (data.contract_id) {
                formData.append('contract_id', data.contract_id.toString())
            }

            // Prepare and append profile data
            const profileData = prepareProfileData(data.profile_data)
            if (Object.keys(profileData).length > 0) {
                formData.append('profile_data', JSON.stringify(profileData))
            }

            // Append document types
            if (selectedDocumentTypes.length > 0) {
                formData.append('document_types', JSON.stringify(selectedDocumentTypes))
            }

            // Append files
            if (profileImage) {
                formData.append('profile_image', profileImage)
            }

            if (documents.length > 0) {
                documents.forEach((doc) => {
                    formData.append('documents[]', doc)
                })
            }

            // Dispatch create officer action
            const result = await dispatch(createGuard(formData))

            if (createGuard.fulfilled.match(result)) {
                await SweetAlertService.success(
                    'Security Officer Created Successfully',
                    `${data.full_name} has been created with code: ${autoGeneratedCode}`,
                    { timer: 2000, showConfirmButton: false }
                )

                resetForm()
                const newCode = await generateGuardCode()
                setAutoGeneratedCode(newCode)
                setValue("guard_code", newCode)

                await dispatch(fetchGuards({
                    page: 1,
                    per_page: 10,
                    sort_by: 'created_at',
                    sort_order: 'desc'
                }))

                onSuccess?.()
                handleDialogClose(false)
            } else {
                const errorMessage = (result.payload as string) || 'Failed to create guard'
                throw new Error(errorMessage)
            }
        } catch (error) {
            await SweetAlertService.error(
                'Creation Failed',
                error instanceof Error ? error.message : 'There was an error creating the guard. Please try again.'
            )
            console.error('Error creating guard:', error)
        } finally {
            setIsSubmitting(false)
        }
    }

    // Step validation
    const validateStep = useCallback(async (currentStep: number): Promise<boolean> => {
        let fieldsToValidate: (keyof GuardFormData)[] = []

        if (currentStep === 1) {
            fieldsToValidate = [
                'full_name', 'phone', 'gender',
                'employee_company_card_number', 'address',
                'city', 'state', 'country', 'zip_code'
            ]
        } else if (currentStep === 2) {
            fieldsToValidate = ['joining_date']

            // Also validate profile_data fields
            const profileData = watch('profile_data')
            if (profileData?.current_address || profileData?.current_city ||
                profileData?.current_state || profileData?.current_country || profileData?.current_zip_code) {
                // If any current address field is filled, validate ZIP code if provided
                if (profileData.current_zip_code && !validateUSZipCode(profileData.current_zip_code)) {
                    SweetAlertService.warning(
                        'Invalid ZIP Code',
                        'Please enter a valid US ZIP code for current address (e.g., 12345 or 12345-6789)'
                    )
                    return false
                }
            }
        }

        const result = await triggerValidation(fieldsToValidate, { shouldFocus: true })
        return result
    }, [triggerValidation, watch, validateUSZipCode])

    const nextStep = useCallback(async () => {
        const isValid = await validateStep(step)
        if (isValid) {
            setStep(step + 1)
        } else {
            await SweetAlertService.warning(
                'Incomplete Information',
                'Please fill in all required fields correctly before proceeding.',
                {
                    timer: 3000,
                    showConfirmButton: true,
                    confirmButtonText: 'OK'
                }
            )
        }
    }, [step, validateStep])

    const prevStep = useCallback(() => {
        setStep(step - 1)
    }, [step])

    const getCurrentDate = useCallback((): string => {
        return new Date().toISOString().split('T')[0]
    }, [])

    const getMinDate = useCallback((): string => {
        const minDate = new Date()
        minDate.setFullYear(minDate.getFullYear() - 100)
        return minDate.toISOString().split('T')[0]
    }, [])

    return (
        <Dialog open={isOpen} onOpenChange={handleDialogClose}>
            <DialogTrigger asChild>
                {trigger}
            </DialogTrigger>

            <DialogContent className="sm:max-w-[1200px] w-[95vw] max-w-[95vw] mx-auto max-h-[90vh] overflow-y-auto dark:bg-gray-900 p-4 sm:p-6">
                <DialogTitle className="sr-only">Add Security Officer</DialogTitle>

                {/* Header */}
                <div className="flex items-center gap-2 text-lg font-semibold mb-6">
                    <Image src="/images/logo.png" alt="Logo" width={24} height={24} />
                    <span className="whitespace-nowrap">Add Security Officer</span>
                </div>

                {/* Progress Steps */}
                <div className="flex items-center justify-center mb-6">
                    <div className="flex items-center space-x-2">
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 1 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'
                            }`}>
                            <User size={20} />
                        </div>
                        <div className={`w-16 h-1 ${step >= 2 ? 'bg-blue-600' : 'bg-gray-200'}`} />
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 2 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'
                            }`}>
                            <Briefcase size={20} />
                        </div>
                        <div className={`w-16 h-1 ${step >= 3 ? 'bg-blue-600' : 'bg-gray-200'}`} />
                        <div className={`flex items-center justify-center w-10 h-10 rounded-full ${step >= 3 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'
                            }`}>
                            <FileText size={20} />
                        </div>
                    </div>
                </div>

                <form onSubmit={handleSubmit(onSubmit)}>
                    {/* Step 1: Basic Information */}
                    {step === 1 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <User size={20} />
                                Basic Information
                            </h3>

                            {/* Guard Code Section */}
                            <div className="mb-6 bg-blue-50 dark:bg-gray-800 rounded-lg p-4">
                                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                                    <div>
                                        <h4 className="font-semibold text-gray-700 dark:text-gray-300">
                                            Officer ID
                                        </h4>
                                        <p className="text-sm text-gray-600 dark:text-gray-400">
                                            This ID is automatically generated
                                        </p>
                                    </div>

                                    <div className="flex items-center gap-2">
                                        <div className="relative">
                                            <input
                                                ref={guardCodeRef}
                                                type="text"
                                                value={autoGeneratedCode}
                                                readOnly
                                                className="w-full px-4 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg font-mono text-lg font-bold text-center"
                                            />
                                            {isGeneratingCode && (
                                                <div className="absolute inset-0 flex items-center justify-center bg-white bg-opacity-80">
                                                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600" />
                                                </div>
                                            )}
                                        </div>

                                        <div className="flex gap-1">
                                            <Button
                                                type="button"
                                                size="sm"
                                                variant="outline"
                                                onClick={copyGuardCode}
                                                className="h-9"
                                            >
                                                <Copy size={16} />
                                            </Button>
                                            <Button
                                                type="button"
                                                size="sm"
                                                variant="outline"
                                                onClick={regenerateGuardCode}
                                                disabled={isGeneratingCode}
                                                className="h-9"
                                            >
                                                Regenerate
                                            </Button>
                                        </div>
                                    </div>
                                </div>

                                {/* Hidden input for form submission */}
                                <input
                                    type="hidden"
                                    {...register("guard_code")}
                                    value={autoGeneratedCode}
                                />
                            </div>

                            {/* First Row - Personal Info */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                <Controller
                                    name="full_name"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Full Name *"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            error={errors.full_name?.message}
                                        />
                                    )}
                                />

                                <Controller
                                    name="phone"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Phone Number *"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            type="tel"
                                            error={errors.phone?.message}
                                        />
                                    )}
                                />

                                <Controller
                                    name="email"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Email"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            type="email"
                                            error={errors.email?.message}
                                        />
                                    )}
                                />

                                <Controller
                                    name="gender"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelSelect
                                            label="Gender *"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            error={errors.gender?.message}
                                        >
                                            <option value="">Select...</option>
                                            <option value="male">Male</option>
                                            <option value="female">Female</option>
                                            <option value="other">Other</option>
                                        </FloatingLabelSelect>
                                    )}
                                />
                            </div>

                            {/* Second Row - Card & License Info */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                <Controller
                                    name="employee_company_card_number"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Security Officer Card Number *"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            error={errors.employee_company_card_number?.message}
                                        />
                                    )}
                                />

                                <Controller
                                    name="driver_license"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Driver's License"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                        />
                                    )}
                                />

                                <Controller
                                    name="date_of_birth"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Date of Birth"
                                            type="date"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            max={getCurrentDate()}
                                            min={getMinDate()}
                                        />
                                    )}
                                />

                                <Controller
                                    name="contract_id"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Contract Number"
                                            type="number"
                                            value={field.value?.toString() || ''}
                                            onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : null)}
                                            error={errors.contract_id?.message}
                                        />
                                    )}
                                />
                            </div>

                            {/* Third Row - Address Fields - Address, City, State, Country, ZIP Code */}
                            <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 mb-6">
                                {/* Address - Takes more space */}
                                <div className="lg:col-span-4">
                                    <Controller
                                        name="address"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Address *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.address?.message}
                                            />
                                        )}
                                    />
                                </div>

                                {/* City */}
                                <div className="lg:col-span-2">
                                    <Controller
                                        name="city"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="City *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.city?.message}
                                            />
                                        )}
                                    />
                                </div>

                                {/* State */}
                                <div className="lg:col-span-2">
                                    <Controller
                                        name="state"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="State *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.state?.message}
                                            >
                                                <option value="">Select State</option>
                                                {US_STATES.map(state => (
                                                    <option key={state} value={state}>
                                                        {state}
                                                    </option>
                                                ))}
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>

                                {/* Country */}
                                <div className="lg:col-span-2">
                                    <Controller
                                        name="country"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Country *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.country?.message}
                                            >
                                                <option value="">Select Country</option>
                                                {COUNTRIES.map(country => (
                                                    <option key={country.code} value={country.name}>
                                                        {country.name}
                                                    </option>
                                                ))}
                                            </FloatingLabelSelect>
                                        )}
                                    />
                                </div>

                                {/* ZIP Code */}
                                <div className="lg:col-span-2">
                                    <Controller
                                        name="zip_code"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="ZIP Code *"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                error={errors.zip_code?.message}
                                                placeholder="12345 or 12345-6789"
                                            />
                                        )}
                                    />
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Step 2: Officer Information */}
                    {step === 2 && (
                        <div className="space-y-6">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <Briefcase size={20} />
                                Officer Information
                            </h3>

                            {/* First Row */}
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                <Controller
                                    name="joining_date"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="Start Date *"
                                            type="date"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            max={getCurrentDate()}
                                            error={errors.joining_date?.message}
                                        />
                                    )}
                                />

                                <Controller
                                    name="license_expiry_date"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="License Expiration Date"
                                            type="date"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            min={getCurrentDate()}
                                        />
                                    )}
                                />

                                <Controller
                                    name="issuing_source"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelSelect
                                            label="Issuing Authority"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                        >
                                            <option value="">Select...</option>
                                            <optgroup label="USA States">
                                                {US_STATES.map(state => (
                                                    <option key={state} value={state.toLowerCase().replace(/\s+/g, "_")}>
                                                        {state}
                                                    </option>
                                                ))}
                                            </optgroup>
                                        </FloatingLabelSelect>
                                    )}
                                />

                                <Controller
                                    name="guard_type_id"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelSelect
                                            label="Officer Classification"
                                            value={field.value?.toString() || ''}
                                            onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : null)}
                                            error={errors.guard_type_id?.message}
                                        >
                                            <option value="">Select Security Officer Type</option>
                                            {isLoadingGuardTypes ? (
                                                <option value="" disabled>Loading officer types...</option>
                                            ) : guardTypes.length > 0 ? (
                                                guardTypes.map((type) => (
                                                    <option key={type.id} value={type.id}>
                                                        {type.name}
                                                    </option>
                                                ))
                                            ) : (
                                                <option value="" disabled>No officer types available</option>
                                            )}
                                        </FloatingLabelSelect>
                                    )}
                                />
                            </div>

                            {/* Password */}
                            <div className="mb-6">
                                <Controller
                                    name="password"
                                    control={control}
                                    render={({ field }) => (
                                        <FloatingLabelInput
                                            label="System Access Password"
                                            type="password"
                                            value={field.value || ''}
                                            onChange={field.onChange}
                                            placeholder="Min. 6 characters"
                                            error={errors.password?.message}
                                        />
                                    )}
                                />
                            </div>

                            {/* Profile Data Section */}
                            <div className="bg-blue-50 dark:bg-gray-800 rounded-lg p-6 mb-6">
                                <h4 className="font-semibold mb-4">Profile Details</h4>

                                {/* Personal Information */}
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                    <Controller
                                        name="profile_data.country_of_origin"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Country of Citizenship"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            >
                                                <option value="">Select...</option>
                                                {COUNTRIES.map(country => (
                                                    <option key={country.code} value={country.name}>
                                                        {country.name}
                                                    </option>
                                                ))}
                                            </FloatingLabelSelect>
                                        )}
                                    />

                                    <Controller
                                        name="profile_data.national_id_number"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Social Security Number"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Current Location - Address, City, State, Country, ZIP Code */}
                                <div className="mb-6">
                                    <h5 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">Current Address</h5>
                                    <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
                                        {/* Current Address */}
                                        <div className="lg:col-span-4">
                                            <Controller
                                                name="profile_data.current_address"
                                                control={control}
                                                render={({ field }) => (
                                                    <FloatingLabelInput
                                                        label="Current Address"
                                                        value={field.value || ''}
                                                        onChange={field.onChange}
                                                    />
                                                )}
                                            />
                                        </div>

                                        {/* Current City */}
                                        <div className="lg:col-span-2">
                                            <Controller
                                                name="profile_data.current_city"
                                                control={control}
                                                render={({ field }) => (
                                                    <FloatingLabelInput
                                                        label="Current City"
                                                        value={field.value || ''}
                                                        onChange={field.onChange}
                                                    />
                                                )}
                                            />
                                        </div>

                                        {/* Current State */}
                                        <div className="lg:col-span-2">
                                            <Controller
                                                name="profile_data.current_state"
                                                control={control}
                                                render={({ field }) => (
                                                    <FloatingLabelSelect
                                                        label="Current State"
                                                        value={field.value || ''}
                                                        onChange={field.onChange}
                                                    >
                                                        <option value="">Select State</option>
                                                        {US_STATES.map(state => (
                                                            <option key={state} value={state}>
                                                                {state}
                                                            </option>
                                                        ))}
                                                    </FloatingLabelSelect>
                                                )}
                                            />
                                        </div>

                                        {/* Current Country */}
                                        <div className="lg:col-span-2">
                                            <Controller
                                                name="profile_data.current_country"
                                                control={control}
                                                render={({ field }) => (
                                                    <FloatingLabelSelect
                                                        label="Current Country"
                                                        value={field.value || ''}
                                                        onChange={field.onChange}
                                                    >
                                                        <option value="">Select Country</option>
                                                        {COUNTRIES.map(country => (
                                                            <option key={country.code} value={country.name}>
                                                                {country.name}
                                                            </option>
                                                        ))}
                                                    </FloatingLabelSelect>
                                                )}
                                            />
                                        </div>

                                        {/* Current ZIP Code */}
                                        <div className="lg:col-span-2">
                                            <Controller
                                                name="profile_data.current_zip_code"
                                                control={control}
                                                render={({ field }) => (
                                                    <FloatingLabelInput
                                                        label="Current ZIP Code"
                                                        value={field.value || ''}
                                                        onChange={field.onChange}
                                                        placeholder="12345 or 12345-6789"
                                                    />
                                                )}
                                            />
                                        </div>
                                    </div>
                                </div>

                                {/* Languages */}
                                <div className="mb-6">
                                    <label className="block text-sm font-medium mb-2">Languages</label>
                                    <div className="flex gap-2 mb-2">
                                        <input
                                            type="text"
                                            value={currentLanguage}
                                            onChange={(e) => setCurrentLanguage(e.target.value)}
                                            onKeyDown={(e) => handleKeyDown(e, 'language')}
                                            placeholder="Type language and press Enter"
                                            className="flex-1 px-3 py-2 border rounded-md dark:bg-gray-700 dark:border-gray-600"
                                        />
                                        <Button
                                            type="button"
                                            onClick={addLanguage}
                                            variant="outline"
                                        >
                                            <Plus size={16} />
                                        </Button>
                                    </div>

                                    {languages.length > 0 && (
                                        <div className="flex flex-wrap gap-2">
                                            {languages.map((language, index) => (
                                                <div key={index} className="flex items-center gap-1 bg-blue-100 text-blue-800 px-3 py-1 rounded-full">
                                                    {language}
                                                    <button
                                                        type="button"
                                                        onClick={() => removeLanguage(language)}
                                                        className="text-blue-600 hover:text-blue-800"
                                                    >
                                                        <X size={14} />
                                                    </button>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </div>

                                {/* Visa Information */}
                                <div className="mb-6">
                                    <label className="block text-sm font-medium mb-2">Work Authorization Countries</label>
                                    <div className="flex gap-2 mb-2">
                                        <input
                                            type="text"
                                            value={currentVisaCountry}
                                            onChange={(e) => setCurrentVisaCountry(e.target.value)}
                                            onKeyDown={(e) => handleKeyDown(e, 'visaCountry')}
                                            placeholder="Type country and press Enter"
                                            className="flex-1 px-3 py-2 border rounded-md dark:bg-gray-700 dark:border-gray-600"
                                        />
                                        <Button
                                            type="button"
                                            onClick={addVisaCountry}
                                            variant="outline"
                                        >
                                            <Plus size={16} />
                                        </Button>
                                    </div>

                                    {visaCountries.length > 0 && (
                                        <div className="flex flex-wrap gap-2">
                                            {visaCountries.map((country, index) => (
                                                <div key={index} className="flex items-center gap-1 bg-green-100 text-green-800 px-3 py-1 rounded-full">
                                                    {country}
                                                    <button
                                                        type="button"
                                                        onClick={() => removeVisaCountry(country)}
                                                        className="text-green-600 hover:text-green-800"
                                                    >
                                                        <X size={14} />
                                                    </button>
                                                </div>
                                            ))}
                                        </div>
                                    )}

                                    <div className="mt-4">
                                        <Controller
                                            name="profile_data.visa_expiry_date"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelInput
                                                    label="Visa Expiry Date"
                                                    type="date"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                    min={getCurrentDate()}
                                                />
                                            )}
                                        />
                                    </div>
                                </div>

                                {/* Education Information */}
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                                    <Controller
                                        name="profile_data.highest_education_level"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelSelect
                                                label="Highest Education"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            >
                                                <option value="">Select...</option>
                                                <option value="high_school">High School</option>
                                                <option value="diploma">Diploma</option>
                                                <option value="associate">Associate Degree</option>
                                                <option value="bachelor">Bachelor Degree</option>
                                                <option value="master">Master Degree</option>
                                                <option value="phd">PhD</option>
                                            </FloatingLabelSelect>
                                        )}
                                    />

                                    <Controller
                                        name="profile_data.education_field"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Education Field"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                placeholder="e.g., Criminal Justice"
                                            />
                                        )}
                                    />

                                    <Controller
                                        name="profile_data.institution_name"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Institution Name"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                placeholder="e.g., University Name"
                                            />
                                        )}
                                    />

                                    <Controller
                                        name="profile_data.graduation_year"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Graduation Year"
                                                type="number"
                                                value={field.value?.toString() || ''}
                                                onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : null)}
                                                min="1900"
                                                max={new Date().getFullYear()}
                                                placeholder="YYYY"
                                            />
                                        )}
                                    />
                                </div>

                                {/* Experience and Skills */}
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                                    <Controller
                                        name="profile_data.experience_years"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Experience (years)"
                                                type="number"
                                                min="0"
                                                value={field.value?.toString() || ''}
                                                onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : 0)}
                                            />
                                        )}
                                    />

                                    <Controller
                                        name="profile_data.skills"
                                        control={control}
                                        render={({ field }) => (
                                            <FloatingLabelInput
                                                label="Skills"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                                placeholder="e.g., First Aid, Surveillance, Combat"
                                            />
                                        )}
                                    />
                                </div>

                                {/* Checkboxes */}
                                <div className="flex gap-6 mb-6">
                                    <label className="flex items-center gap-2">
                                        <input
                                            type="checkbox"
                                            {...register("profile_data.has_work_permit")}
                                            className="rounded"
                                        />
                                        <span>Has Work Permit</span>
                                    </label>

                                    <label className="flex items-center gap-2">
                                        <input
                                            type="checkbox"
                                            {...register("profile_data.has_security_training")}
                                            className="rounded"
                                        />
                                        <span>Security Certification</span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Step 3: Documents & Final Details */}
                    {step === 3 && (
                        <div className="space-y-8">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <FileText size={20} />
                                Documents & Final Details
                            </h3>

                            {/* Required Documents with File Upload - Responsive Grid */}
                            <div>
                                <label className="block text-sm font-medium mb-4">Required Documents</label>
                                <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">
                                    {DOCUMENT_TYPES.map((docType) => {
                                        const isSelected = selectedDocumentTypes.includes(docType.id);
                                        const documentIndex = documents.findIndex(doc =>
                                            doc.name.includes(docType.id) || doc.name.includes(docType.name)
                                        );

                                        return (
                                            <div
                                                key={docType.id}
                                                className={`border rounded-xl p-4 transition-all ${isSelected
                                                    ? 'border-blue-300 bg-blue-50/50 dark:bg-blue-900/10'
                                                    : 'hover:border-gray-300'
                                                    }`}
                                            >
                                                <div className="flex items-start gap-3">
                                                    <input
                                                        type="checkbox"
                                                        id={`doc-${docType.id}`}
                                                        checked={isSelected}
                                                        onChange={() => handleDocumentTypeChange(docType.id)}
                                                        className="rounded w-4 h-4 text-blue-600 mt-1 flex-shrink-0"
                                                    />
                                                    <label
                                                        htmlFor={`doc-${docType.id}`}
                                                        className="text-sm font-medium cursor-pointer flex-1 flex items-center gap-1"
                                                    >
                                                        {docType.name}
                                                        {docType.required && (
                                                            <span className="text-red-500 text-xs">*</span>
                                                        )}
                                                    </label>
                                                </div>

                                                {/* File Upload Section - Visible only when checkbox is selected */}
                                                {isSelected && (
                                                    <div className="mt-4 ml-7">
                                                        {documentIndex === -1 ? (
                                                            <div className="space-y-2">
                                                                <input
                                                                    type="file"
                                                                    id={`file-${docType.id}`}
                                                                    onChange={(e) => {
                                                                        const file = e.target.files?.[0];
                                                                        if (file) {
                                                                            // Validate file type
                                                                            const validTypes = [
                                                                                'application/pdf',
                                                                                'image/jpeg',
                                                                                'image/jpg',
                                                                                'image/png',
                                                                                'application/msword',
                                                                                'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                                                                            ];

                                                                            if (!validTypes.includes(file.type)) {
                                                                                SweetAlertService.error(
                                                                                    'Invalid File Type',
                                                                                    'Please upload PDF, JPG, PNG, or DOC files only'
                                                                                );
                                                                                return;
                                                                            }

                                                                            if (file.size > 10 * 1024 * 1024) {
                                                                                SweetAlertService.error(
                                                                                    'File Too Large',
                                                                                    'Please upload a file smaller than 10MB'
                                                                                );
                                                                                return;
                                                                            }

                                                                            // Add document with type identifier
                                                                            const documentWithType = new File(
                                                                                [file],
                                                                                `${docType.name}-${file.name}`,
                                                                                { type: file.type }
                                                                            );
                                                                            setDocuments(prev => [...prev, documentWithType]);

                                                                            // Clear the input value so the same file can be selected again if needed
                                                                            e.target.value = '';
                                                                        }
                                                                    }}
                                                                    className="hidden"
                                                                    accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"
                                                                />

                                                                <label
                                                                    htmlFor={`file-${docType.id}`}
                                                                    className="block w-full cursor-pointer"
                                                                >
                                                                    <div className="border-2 border-dashed rounded-lg p-4 hover:border-blue-400 hover:bg-blue-50/50 transition-all text-center">
                                                                        <UploadCloud className="w-6 h-6 text-gray-400 mx-auto mb-2" />
                                                                        <span className="text-sm text-gray-600 block mb-1">Click to upload</span>
                                                                        <span className="text-xs text-gray-400">PDF, JPG, PNG, DOC (max 10MB)</span>
                                                                    </div>
                                                                </label>
                                                            </div>
                                                        ) : (
                                                            <div className="flex items-center justify-between bg-white dark:bg-gray-800 p-3 rounded-lg border">
                                                                <div className="flex items-center gap-2 min-w-0 flex-1">
                                                                    <FileText size={16} className="text-blue-500 flex-shrink-0" />
                                                                    <span className="text-sm truncate max-w-[150px] sm:max-w-[180px]" title={documents[documentIndex].name}>
                                                                        {documents[documentIndex].name}
                                                                    </span>
                                                                </div>
                                                                <button
                                                                    type="button"
                                                                    onClick={() => {
                                                                        setDocuments(prev => prev.filter((_, i) => i !== documentIndex));
                                                                    }}
                                                                    className="text-red-500 hover:text-red-700 p-1 hover:bg-red-50 rounded-full transition-all flex-shrink-0"
                                                                    title="Remove file"
                                                                >
                                                                    <X size={16} />
                                                                </button>
                                                            </div>
                                                        )}
                                                    </div>
                                                )}
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Profile Photo and Emergency Contact in 2 Columns */}
                            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                                {/* Profile Photo */}
                                <div className="border-2 border-dashed rounded-xl p-6">
                                    <h4 className="font-medium mb-4 flex items-center gap-2">
                                        <User size={18} className="text-blue-500" />
                                        Profile Photo
                                    </h4>
                                    <div className="flex flex-col items-center">
                                        <div className="relative mb-4">
                                            <input
                                                type="file"
                                                id="profileImage"
                                                onChange={handleProfileImageUpload}
                                                className="hidden"
                                                accept="image/*"
                                            />
                                            <label htmlFor="profileImage" className="cursor-pointer">
                                                <div className="relative w-32 h-32 rounded-full border-2 border-dashed border-gray-300 flex flex-col items-center justify-center bg-white hover:border-blue-400 hover:bg-blue-50/50 transition-all dark:bg-gray-800 dark:border-gray-600">
                                                    {profileImage ? (
                                                        <>
                                                            <Image
                                                                src={URL.createObjectURL(profileImage)}
                                                                alt="Profile preview"
                                                                width={128}
                                                                height={128}
                                                                className="rounded-full object-cover w-full h-full"
                                                            />
                                                            <div className="absolute inset-0 bg-black bg-opacity-50 rounded-full flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
                                                                <Plus className="w-8 h-8 text-white" />
                                                            </div>
                                                        </>
                                                    ) : (
                                                        <>
                                                            <Plus className="w-8 h-8 text-gray-400 mb-2" />
                                                            <p className="text-sm text-gray-600 dark:text-gray-400 text-center px-2">
                                                                Upload Photo
                                                            </p>
                                                        </>
                                                    )}
                                                </div>
                                            </label>
                                        </div>
                                        {profileImage && (
                                            <button
                                                type="button"
                                                onClick={() => setProfileImage(null)}
                                                className="mt-2 text-red-500 hover:text-red-700 text-sm flex items-center gap-1 px-3 py-1 rounded-full hover:bg-red-50 transition-all"
                                            >
                                                <X size={14} /> Remove Photo
                                            </button>
                                        )}
                                        <p className="text-xs text-gray-500 mt-3 text-center">
                                            JPG, PNG, GIF. Max 5MB. Square image recommended.
                                        </p>
                                    </div>
                                </div>

                                {/* Emergency Contact */}
                                <div className="bg-yellow-50 dark:bg-gray-800 rounded-xl p-6">
                                    <h4 className="font-semibold mb-4 flex items-center gap-2">
                                        <Briefcase size={18} className="text-yellow-600" />
                                        Emergency Contact
                                    </h4>
                                    <div className="space-y-4">
                                        <Controller
                                            name="profile_data.emergency_contact_name"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelInput
                                                    label="Contact Name"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                />
                                            )}
                                        />

                                        <Controller
                                            name="profile_data.emergency_contact_phone"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelInput
                                                    label="Contact Phone"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                    type="tel"
                                                />
                                            )}
                                        />

                                        <Controller
                                            name="profile_data.emergency_contact_relation"
                                            control={control}
                                            render={({ field }) => (
                                                <FloatingLabelInput
                                                    label="Relationship"
                                                    value={field.value || ''}
                                                    onChange={field.onChange}
                                                    placeholder="e.g., Spouse, Parent"
                                                />
                                            )}
                                        />
                                    </div>
                                </div>
                            </div>

                            {/* Notes and Status in 2 Columns */}
                            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                                {/* Notes - spans 2 columns */}
                                <div className="lg:col-span-2">
                                    <label className="block text-sm font-medium mb-2">Additional Notes</label>
                                    <Controller
                                        name="profile_data.notes"
                                        control={control}
                                        render={({ field }) => (
                                            <Textarea
                                                {...field}
                                                placeholder="Any additional information about the guard..."
                                                className="w-full h-32 resize-none dark:bg-gray-700 dark:border-gray-600"
                                                value={field.value || ''}
                                                onChange={field.onChange}
                                            />
                                        )}
                                    />
                                </div>

                                {/* Status */}
                                <div className="lg:col-span-1">
                                    <label className="block text-sm font-medium mb-2">Security Officer Status</label>
                                    <div className="border rounded-xl p-6 h-32 flex items-center justify-center bg-gray-50/50 dark:bg-gray-800/50">
                                        <label className="flex items-center gap-3 cursor-pointer">
                                            <input
                                                type="checkbox"
                                                {...register("is_active")}
                                                defaultChecked={true}
                                                className="rounded w-5 h-5 text-blue-600"
                                            />
                                            <span className="text-base text-gray-700 dark:text-gray-300">
                                                Active Officer
                                            </span>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            {/* Uploaded Documents Summary */}
                            {documents.length > 0 && (
                                <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl p-6">
                                    <div className="flex items-center justify-between mb-4">
                                        <h4 className="font-medium flex items-center gap-2">
                                            <FileText size={18} className="text-blue-500" />
                                            Uploaded Documents ({documents.length})
                                        </h4>
                                        <Button
                                            type="button"
                                            variant="ghost"
                                            size="sm"
                                            onClick={() => setDocuments([])}
                                            className="text-red-500 hover:text-red-700"
                                        >
                                            Clear All
                                        </Button>
                                    </div>
                                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                                        {documents.map((doc, index) => (
                                            <div
                                                key={index}
                                                className="bg-white dark:bg-gray-900 rounded-lg p-3 flex items-center justify-between group hover:shadow-md transition-all border"
                                            >
                                                <div className="flex items-center gap-2 min-w-0 flex-1">
                                                    <FileText size={16} className="text-blue-500 flex-shrink-0" />
                                                    <span className="text-sm truncate" title={doc.name}>
                                                        {doc.name.length > 30 ? doc.name.substring(0, 30) + '...' : doc.name}
                                                    </span>
                                                </div>
                                                <button
                                                    type="button"
                                                    onClick={() => removeDocument(index)}
                                                    className="text-red-500 hover:text-red-700 opacity-0 group-hover:opacity-100 transition-opacity p-1 hover:bg-red-50 rounded-full"
                                                    title="Remove file"
                                                >
                                                    <X size={14} />
                                                </button>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                    )}

                    {/* Navigation Buttons */}
                    <div className="flex justify-between items-center pt-6 border-t dark:border-gray-700">
                        {step > 1 ? (
                            <Button
                                type="button"
                                variant="outline"
                                onClick={prevStep}
                            >
                                ← Back
                            </Button>
                        ) : (
                            <Button
                                type="button"
                                variant="outline"
                                onClick={() => handleDialogClose(false)}
                            >
                                Cancel
                            </Button>
                        )}

                        {step < 3 ? (
                            <Button
                                type="button"
                                onClick={nextStep}
                            >
                                Continue →
                            </Button>
                        ) : (
                            <div className="flex gap-2">
                                <Button
                                    type="button"
                                    variant="outline"
                                    onClick={() => handleDialogClose(false)}
                                >
                                    Cancel
                                </Button>
                                <Button
                                    type="submit"
                                    disabled={isSubmitting}
                                    className="bg-green-600 hover:bg-green-700"
                                >
                                    {isSubmitting ? (
                                        <>
                                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                                            Creating...
                                        </>
                                    ) : (
                                        'Create Security Officer'
                                    )}
                                </Button>
                            </div>
                        )}
                    </div>
                </form>
            </DialogContent>
        </Dialog>
    )
}