// import { Incident } from "@/app/types/incident";

// export const incidents: Incident[] = [
//   {
//     row: 1,
//     tracking_code: "Tracking code",
//     title: "Title",
//     site_name: "GBR",
//     reporter: "Client",
//     client_name: "Mile Anderson",
//     guard_name: "James Rabin",
//     date: "10/31/2025",
//     time: "22:54",
//     status: "Reviewed",
//   },
//   {
//     row: 2,
//     tracking_code: "Tracking code",
//     title: "Title",
//     site_name: "GBR",
//     reporter: "Guard",
//     client_name: "Mile Anderson",
//     guard_name: "James Rabin",
//     date: "10/31/2025",
//     time: "22:54",
//     status: "Unreviewed",
//   },
//   {
//     row: 3,
//     tracking_code: "Tracking code",
//     title: "Title",
//     site_name: "GBR",
//     reporter: "Client",
//     client_name: "Mile Anderson",
//     guard_name: "James Rabin",
//     date: "10/31/2025",
//     time: "22:54",
//     status: "Unreviewed",
//   },
//   {
//     row: 4,
//     tracking_code: "Tracking code",
//     title: "Title",
//     site_name: "GBR",
//     reporter: "Admin",
//     client_name: "Mile Anderson",
//     guard_name: "James Rabin",
//     date: "10/31/2025",
//     time: "22:54",
//     status: "Reviewed",
//   },
//   {
//     row: 5,
//     tracking_code: "Tracking code",
//     title: "Title",
//     site_name: "GBR",
//     reporter: "Admin",
//     client_name: "Mile Anderson",
//     guard_name: "James Rabin",
//     date: "10/31/2025",
//     time: "22:54",
//     status: "Unreviewed",
//   },
//   {
//     row: 6,
//     tracking_code: "Tracking code",
//     title: "Title",
//     site_name: "GBR",
//     reporter: "Guard",
//     client_name: "Mile Anderson",
//     guard_name: "James Rabin",
//     date: "10/31/2025",
//     time: "22:54",
//     status: "Unreviewed",
//   },
// ];
